### PR TITLE
Cypher query options only settable in the context

### PR DESCRIPTION
**Pull request by darrellwarde**
# Description

Following the pattern established by `sessionConfig`, this moves `cypherQueryOptions` into the context only, due to the fact that it is an option set per-request, in the wrapper.

## Complexity

Complexity: Low

### CODE REVIEW

**Comment by neo4j-team-graphql** [comment]
Looks like you've updated the documentation!

Check out your changes at https://neo4j-graphql-docs-3674.surge.sh

**Comment by neo4j-team-graphql** [comment]
Made some changes to the Neo4j GraphQL Toolbox? Or made some changes to the core library perhaps?

Check out your changes at https://neo4j-graphql-toolbox-3674.surge.sh

Use for instance a local dbms hosted on [Neo4j Desktop](https://neo4j.com/download/) or a cloud-hosted [Aura Free](https://neo4j.com/cloud/aura-free/) dbms.

**Review by MacondoExpress — COMMENTED** [review]
LGTM! Just a thing, I believe there are other mentions in the documentation where the previous options are present: "troubleshooting", "api-reference".

**Comment by darrellwarde** [comment]
> LGTM! Just a thing, I believe there are other mentions in the documentation where the previous definition is present: "troubleshooting", "api-reference".

I'm going to leave the API reference for now and tidy that up in a subsequent PR!

**Review by MacondoExpress — APPROVED** [review]

**Pull request merged**
