### PR TITLE
fix small errors in example code

### PR DESCRIPTION
**Pull request by camillepradel**
# Description

Fix two simple errors in example code of Custom Resolvers documentation.

# Issue

No issue was created.

# Checklist

The following requirements should have been met (depending on the changes in the branch):

- [ ] Documentation has been updated
- [ ] TCK tests have been updated
- [ ] Integration tests have been updated
- [x] Example applications have been updated
- [ ] New files have copyright header
- [x] CLA (https://neo4j.com/developer/cla/) has been signed

### CODE REVIEW

**Comment by oskarhane** [comment]
Hi and thanks for your contribution @camillepradel!
For us to be able to accept your contribution we'd need you to sign the CLA (see link in your description).

**Comment by camillepradel** [comment]
> Hi and thanks for your contribution @camillepradel!
> For us to be able to accept your contribution we'd need you to sign the CLA (see link in your description).

I just sent it!

**Comment by neo4j-team-graphql** [comment]
Looks like you've updated the documentation!

Check out your changes at https://neo4j-graphql-docs-467.surge.sh

**Review by oskarhane — APPROVED** [review]
Thanks again @camillepradel

**Pull request merged**
