### PR TITLE
Change minimum database version to 4.1.5

### PR DESCRIPTION
**Pull request by darrellwarde**
# Description

Following reports that our changes to connect operations no longer work on 4.1.0, I iterated through versions to find the minimum which we now support - 4.1.5 is where all tests start passing.

Also fixes version checking, now uses `semver` package for comparison. For non-semantic APOC version, strips off the trailing number.

Also, now throws all compatibility issues in one error, rather than throwing as soon as it hits each.

Worthwhile adding an integration test pipeline for 4.1.5 exactly (rather than 4.1.x as current, I'm assuming 4.1.9) so we can easily tell if and when we break compatibility? 

# Checklist

The following requirements should have been met (depending on the changes in the branch):

- [ ] Documentation has been updated
- [ ] TCK tests have been updated
- [ ] Integration tests have been updated
- [ ] Example applications have been updated
- [ ] New files have copyright header
- [ ] CLA (https://neo4j.com/developer/cla/) has been signed

### CODE REVIEW

**Review by oskarhane — APPROVED** [review]
Sounds good to add an additional compat test for minimun supported version 👍 
Can you create a card for it (or add the test job in the pipe)?

**Comment by darrellwarde** [comment]
> Sounds good to add an additional compat test for minimun supported version 👍
> Can you create a card for it (or add the test job in the pipe)?

I sure can, will add to the pipeline now! 🙂

**Review by danstarns — APPROVED** [review]

**Comment by darrellwarde** [comment]
Made some code changes since approvals - would appreciate a re-review before merging @danstarns @oskarhane. 🙂

**Review by oskarhane — APPROVED** [review]

**Comment by darrellwarde** [comment]
Merging because test failure is on Aura Professional build which isn't actually hooked up to the pipeline yet - need to work around a few unexpected failures there.

**Pull request merged**
