### PR TITLE
Cypher Builder - export `Cypher.Property`

### PR DESCRIPTION
**Pull request by darrellwarde**
# Description

> **Note**
> 
> Please provide a description of the work completed in this PR below

`Cypher.PropertyRef` is currently exposed as a type only. This exports `Cypher.Property` in full, which is a requirement for Authorization.

## Complexity

> **Note**
>
> Please provide an estimated complexity of this PR of either Low, Medium or High

Complexity: Low

### CODE REVIEW

**Comment by darrellwarde** [comment]
@angrykoala, should https://github.com/neo4j/graphql/pull/3106/files#diff-644d9c8b33dc3e7e560dacb7b2025d81ca04e8f22c5fa3baa58010b5bdd24250R41 return type be `Reference` to match the type of the member?

**Comment by neo4j-team-graphql** [comment]
Made some changes to the GraphQL Toolbox? Or made some changes to the core library perhaps?

Check out your changes at https://neo4j-graphql-toolbox-stage-3106.surge.sh

Use for instance a local dbms hosted on [Neo4j Desktop](https://neo4j.com/download/) or a cloud-hosted [Aura Free](https://neo4j.com/cloud/aura-free/) dbms.

**Comment by neo4j-team-graphql** [comment]
# Performance Report

No Performance Changes


<details>
    <summary>Show Full Table</summary>
    
| name | dbHits | old dbHits | time (ms) | old time (ms) | maxRows |
| ---- | ------ | ---------- | --------- | ------------- | ------- |
|  aggregations.TopLevelAggregate | 3403 | 3403 | 38 | 55 | 1134 |
|  aggregations.NestedAggregation | 14551 | 14551 | 83 | 90 | 2174 |
|  aggregations.AggregationWithWhere | 11979 | 11979 | 58 | 65 | 2174 |
|  aggregations.AggregationWhereWithinNestedRelationships | 22116987 | 22116987 | 3493 | 3437 | 2008534 |
|  aggregations.AggregationWhereWithinNestedConnections | 22116987 | 22116987 | 3152 | 3023 | 2008534 |
|  aggregations.NestedCountFromMovieToActors | 9734 | 9734 | 41 | 50 | 2174 |
|  aggregations.NestedCountFromActorsToMovie | 9937 | 9937 | 58 | 54 | 2174 |
|  aggregations.DeeplyNestedCount | 13070335 | 13070331 | 4739 | 4501 | 2008534 |
|  batch-create.BatchCreate | 4200 | 4200 | 212 | 244 | 600 |
|  connect.createAndConnect | 14424 | 14424 | 144 | 179 | 3003 |
|  connections.Connection | 14082 | 14082 | 69 | 148 | 2174 |
|  connections.NestedConnection | 41462 | 41468 | 103 | 166 | 4516 |
|  connections.ConnectionWithSort | 2282 | 2282 | 61 | 72 | 1040 |
|  connections.ConnectionWithSortAndCypher | 2282 | 2282 | 181 | 305 | 1040 |
|  create.SimpleMutation | 7 | 7 | 54 | 64 | 1 |
|  cypher-directive.TopLevelCypherDirective | 116092 | 116092 | 615 | 687 | 12241 |
|  cypher-directive.TopLevelCypherDirectiveWithColumnName | 147611 | 147609 | 190 | 204 | 12241 |
|  delete.SimpleDelete | 19401 | 19401 | 219 | 260 | 1040 |
|  delete.NestedDeleteInUpdate | 22200 | 22200 | 143 | 166 | 2040 |
|  2925.SingleRelationshipFilter | 6468 | 6468 | 39 | 44 | 1040 |
|  2925.NestedSingleRelationshipFilter | 22900 | 22900 | 69 | 121 | 2174 |
|  2925.SingleRelationshipRequiredFilter | 3450 | 3450 | 36 | 38 | 1134 |
|  2925.NestedSingleRelationshipRequiredFilter | 9383 | 9383 | 46 | 66 | 1040 |
|  query.SimpleQuery | 15160 | 15160 | 52 | 60 | 2174 |
|  query.QueryWhere | 9699 | 9705 | 35 | 54 | 2163 |
|  query.SimpleQueryWithNestedWhere | 9877 | 9883 | 49 | 71 | 2163 |
|  query.Nested | 10092037 | 10092037 | 10514 | 11130 | 2008534 |
|  query.NestedWithFilter | 40401 | 40401 | 115 | 121 | 4511 |
|  query.OrFilterOnRelationships | 42711 | 41208 | 176 | 219 | 1660 |
|  query.OrFilterOnRelationshipsAndNested | 35983 | 35543 | 199 | 268 | 1660 |
|  query.QueryWithNestedIn | 13499 | 13211 | 54 | 60 | 1250 |
|  query.NestedConnectionWhere | 9834 | 9834 | 61 | 65 | 2174 |
|  query.DeeplyNestedConnectionWhere | 10029 | 10059 | 71 | 90 | 2174 |
|  query.DeeplyNestedWithRelationshipFilters | 19278 | 19266 | 126 | 155 | 1646 |
|  query.NestedWithRelationshipSingleFilters | 3024400 | 3024400 | 685 | 735 | 1003942 |
|  query.Fulltext | 96 | 96 | 40 | 30 | 16 |
|  query.FulltextWithNestedQuery | 587 | 587 | 46 | 48 | 84 |
|  sorting.SortMultipleTypes | 2513 | 2513 | 73 | 73 | 1040 |
|  sorting.SortMultipleTypesWithCypherWithCypher | 1458 | 1511 | 162 | 263 | 1040 |
|  sorting.SortOnNestedFields | 14082 | 14082 | 61 | 54 | 2174 |
|  sorting.SortDeeplyNestedFields | 42196 | 42196 | 94 | 107 | 4516 |
|  sorting.SortWithTopLevelCypher | 2119 | 2119 | 110 | 205 | 1040 |
|  unions.SimpleUnionQuery | 321 | 321 | 71 | 81 | 35 |
|  unions.SimpleUnionQueryWithMissingFields | 293 | 293 | 74 | 82 | 35 |
|  unions.NestedUnion | 410637 | 410637 | 292 | 366 | 33033 |
|  unions.NestedUnionWithMissingFields | 384611 | 384611 | 268 | 302 | 33033 |
|  update.NestedUpdate | 2119 | 2119 | 72 | 70 | 1040 |

</details>
        
Old Schema Generation: 34.928s
Schema Generation: 34.307s
Old Subgraph Schema Generation: 50.265s
Subgraph Schema Generation: 50.354s

**Comment by angrykoala** [comment]
> @angrykoala, should https://github.com/neo4j/graphql/pull/3106/files#diff-644d9c8b33dc3e7e560dacb7b2025d81ca04e8f22c5fa3baa58010b5bdd24250R41 return type be `Reference` to match the type of the member?

Yeah, I think that's a good idea. Good catch

**Comment by darrellwarde** [comment]
> > @angrykoala, should https://github.com/neo4j/graphql/pull/3106/files#diff-644d9c8b33dc3e7e560dacb7b2025d81ca04e8f22c5fa3baa58010b5bdd24250R41 return type be `Reference` to match the type of the member?
> 
> Yeah, I think that's a good idea. Good catch

I changed the type, but not the name of the method, so it's still called `variable()` - is this okay?

**Review by angrykoala — APPROVED** [review]

**Pull request merged**
