### PR TITLE
Add features.populatedBy.callbacks to deprecate config.callbacks

### PR DESCRIPTION
**Pull request by mjfwebb**
# Description

This PR deprecates the constructor option `config.callbacks` in favour of the new `features.populatedBy.callbacks`

As a small aside, this PR fixes some various "existance" typos.

## Complexity

Low

### CODE REVIEW

**Comment by neo4j-team-graphql** [comment]
Looks like you've updated the documentation!

Check out your changes at https://neo4j-graphql-docs-3085.surge.sh

**Comment by neo4j-team-graphql** [comment]
Made some changes to the GraphQL Toolbox? Or made some changes to the core library perhaps?

Check out your changes at https://neo4j-graphql-toolbox-stage-3085.surge.sh

Use for instance a local dbms hosted on [Neo4j Desktop](https://neo4j.com/download/) or a cloud-hosted [Aura Free](https://neo4j.com/cloud/aura-free/) dbms.

**Comment by neo4j-team-graphql** [comment]
# Performance Report

No Performance Changes


<details>
    <summary>Show Full Table</summary>
    
| name | dbHits | old dbHits | time (ms) | old time (ms) | maxRows |
| ---- | ------ | ---------- | --------- | ------------- | ------- |
|  aggregations.TopLevelAggregate | 3403 | 3403 | 45 | 64 | 1134 |
|  aggregations.NestedAggregation | 14551 | 14551 | 104 | 120 | 2174 |
|  aggregations.AggregationWithWhere | 11979 | 11979 | 71 | 79 | 2174 |
|  aggregations.AggregationWhereWithinNestedRelationships | 22116987 | 22116987 | 3839 | 4156 | 2008534 |
|  aggregations.AggregationWhereWithinNestedConnections | 22116987 | 22116987 | 3581 | 3682 | 2008534 |
|  aggregations.NestedCountFromMovieToActors | 9734 | 9734 | 51 | 74 | 2174 |
|  aggregations.NestedCountFromActorsToMovie | 9937 | 9937 | 74 | 95 | 2174 |
|  aggregations.DeeplyNestedCount | 13070331 | 13070331 | 5797 | 6297 | 2008534 |
|  batch-create.BatchCreate | 4200 | 4200 | 147 | 192 | 600 |
|  connect.createAndConnect | 14424 | 14424 | 190 | 283 | 3003 |
|  connections.Connection | 14082 | 14082 | 96 | 90 | 2174 |
|  connections.NestedConnection | 41462 | 41462 | 140 | 150 | 4516 |
|  connections.ConnectionWithSort | 2282 | 2282 | 90 | 103 | 1040 |
|  connections.ConnectionWithSortAndCypher | 2282 | 2282 | 213 | 359 | 1040 |
|  create.SimpleMutation | 7 | 7 | 65 | 95 | 1 |
|  cypher-directive.TopLevelCypherDirective | 116092 | 116092 | 994 | 1054 | 12241 |
|  cypher-directive.TopLevelCypherDirectiveWithColumnName | 147609 | 147609 | 336 | 314 | 12241 |
|  delete.SimpleDelete | 19401 | 19401 | 389 | 392 | 1040 |
|  delete.NestedDeleteInUpdate | 22200 | 22200 | 181 | 219 | 2040 |
|  2925.SingleRelationshipFilter | 6468 | 6468 | 43 | 163 | 1040 |
|  2925.NestedSingleRelationshipFilter | 22900 | 22900 | 89 | 127 | 2174 |
|  2925.SingleRelationshipRequiredFilter | 3450 | 3450 | 37 | 57 | 1134 |
|  2925.NestedSingleRelationshipRequiredFilter | 9383 | 9383 | 59 | 62 | 1040 |
|  query.SimpleQuery | 15160 | 15160 | 76 | 89 | 2174 |
|  query.QueryWhere | 9715 | 9707 | 38 | 51 | 2167 |
|  query.SimpleQueryWithNestedWhere | 9893 | 9885 | 64 | 69 | 2167 |
|  query.Nested | 10092037 | 10092037 | 11991 | 13115 | 2008534 |
|  query.NestedWithFilter | 40401 | 40401 | 145 | 142 | 4511 |
|  query.OrFilterOnRelationships | 42036 | 43459 | 195 | 269 | 1430 |
|  query.OrFilterOnRelationshipsAndNested | 35933 | 36680 | 249 | 408 | 1430 |
|  query.QueryWithNestedIn | 13928 | 13631 | 73 | 144 | 1395 |
|  query.NestedConnectionWhere | 9834 | 9834 | 64 | 131 | 2174 |
|  query.DeeplyNestedConnectionWhere | 10044 | 9941 | 116 | 125 | 2174 |
|  query.DeeplyNestedWithRelationshipFilters | 19230 | 19200 | 270 | 239 | 1630 |
|  query.NestedWithRelationshipSingleFilters | 3024400 | 3024400 | 823 | 893 | 1003942 |
|  query.Fulltext | 96 | 96 | 30 | 41 | 16 |
|  query.FulltextWithNestedQuery | 587 | 587 | 49 | 60 | 84 |
|  sorting.SortMultipleTypes | 2513 | 2513 | 76 | 82 | 1040 |
|  sorting.SortMultipleTypesWithCypherWithCypher | 1444 | 1471 | 225 | 296 | 1040 |
|  sorting.SortOnNestedFields | 14082 | 14082 | 87 | 96 | 2174 |
|  sorting.SortDeeplyNestedFields | 42196 | 42196 | 126 | 161 | 4516 |
|  sorting.SortWithTopLevelCypher | 2119 | 2119 | 160 | 335 | 1040 |
|  unions.SimpleUnionQuery | 321 | 321 | 84 | 110 | 35 |
|  unions.SimpleUnionQueryWithMissingFields | 293 | 293 | 108 | 85 | 35 |
|  unions.NestedUnion | 410637 | 410637 | 514 | 373 | 33033 |
|  unions.NestedUnionWithMissingFields | 384611 | 384611 | 327 | 383 | 33033 |
|  update.NestedUpdate | 2119 | 2119 | 77 | 81 | 1040 |

</details>
        
Old Schema Generation: 41.100s
Schema Generation: 39.584s
Old Subgraph Schema Generation: 58.239s
Subgraph Schema Generation: 56.328s

**Review by darrellwarde — APPROVED** [review]
I thought I had reviewed this on Friday, sorry! Looks good!

**Pull request merged**
