### PR TITLE
Fix: Pagination on Abstract Connection

### PR DESCRIPTION
**Pull request by dmoree**
# Description

This PR fixes the implementation of pagination for abstract connection types. 

# Checklist

- [x] TCK tests have been updated
- [x] Integration tests have been updated
- [x] CLA (https://neo4j.com/developer/cla/) has been signed

### CODE REVIEW

**Review by darrellwarde — DISMISSED** [review]
To be honest with you, seeing these integration tests working here, I'm not quite sure why we had the conditional logic to do this in the first place! Nice fix, thanks! Sorry we've been a little slow on PRs lately.

**Comment by darrellwarde** [comment]
Just a couple of merge conflicts @dmoree - I hope you don't mind quickly fixing and then we can get this one merged and off your books? 😄

**Comment by dmoree** [comment]
@darrellwarde I'm getting failing tests regarding `neo-push`. It appears as if `neo4j-driver` was never upgraded to `4.4.2`.

**Comment by darrellwarde** [comment]
> @darrellwarde I'm getting failing tests regarding `neo-push`. It appears as if `neo4j-driver` was never upgraded to `4.4.2`.

I was just experiencing this myself actually - don't worry about that here, we'll get that sorted in another PR tomorrow. Thanks for the heads up!

**Comment by dmoree** [comment]
> Just a couple of merge conflicts @dmoree - I hope you don't mind quickly fixing and then we can get this one merged and off your books? 😄

Maybe not the best place but any chance you would also like to get #646 off too?

**Comment by darrellwarde** [comment]
> > Just a couple of merge conflicts @dmoree - I hope you don't mind quickly fixing and then we can get this one merged and off your books? 😄
> 
> 
> 
> Maybe not the best place but any chance you would also like to get #646 off too?

I was intending to get that reviewed by the weekend! Just needs a bit more focus because it looks like things have been shuffled around a bit in there.

**Comment by dmoree** [comment]
I can get those merge conflicts resolved and pushed a bit closer. Thanks a lot.

**Review by darrellwarde — APPROVED** [review]

**Pull request merged**
