### PR TITLE
Check for constraints on additional labels

### PR DESCRIPTION
**Pull request by Liam-Doodson**
# Description

No longer throws an error when running `assertIndexesAndConstraints` with `create: false` if a constraint only exists on an additional label and not the main label.

No longer creates new constraints when running `assertIndexesAndConstraints` with `create: true` if a constraint already exists on an additional label.

## Complexity

Complexity: Low

# Checklist

The following requirements should have been met (depending on the changes in the branch):

- [x] Documentation has been updated
- [x] TCK tests have been updated
- [x] Integration tests have been updated
- [x] Example applications have been updated
- [x] New files have copyright header
- [x] CLA (https://neo4j.com/developer/cla/) has been signed

### CODE REVIEW

**Comment by neo4j-team-graphql** [comment]
Made some changes to the GraphQL Toolbox? Or made some changes to the core library perhaps?

Check out your changes at https://neo4j-graphql-toolbox-stage-2564.surge.sh

Use for instance a local dbms hosted on [Neo4j Desktop](https://neo4j.com/download/) or a cloud-hosted [Aura Free](https://neo4j.com/cloud/aura-free/) dbms.

**Comment by darrellwarde** [comment]
Don't forget to add a changeset! 🙂

**Comment by Liam-Doodson** [comment]
> Don't forget to add a changeset! 🙂

Good spot, just added one!

**Review by darrellwarde — APPROVED** [review]
LGTM! Nice and well tested.

**Pull request merged**
