### PR TITLE
Test/add-docker-for-testing

### PR DESCRIPTION
**Pull request by danstarns**
Adds docker file and a compose for testing. Make sure you turn off your local neo4j instance and run; 

```
docker-compose -f ./docker-compose.test.yml up --build --abort-on-container-exit --exit-code-from test
```

Did it work?

### CODE REVIEW

**Comment by darrellwarde** [comment]
No 🤣  Let's not rush something like this in - I had visions of automating the Docker up/down as part of the setup/teardown scripts of Jest, would be nice to have the familiarity of `yarn test` with lots of fanciness happening under the hood.

**Comment by danstarns** [comment]
@darrellwarde Did you get an error?

**Comment by darrellwarde** [comment]
> @darrellwarde Did you get an error?

I did indeed:

```
Unexpected API error for graphql_neo4j_1 (HTTP code 502)
Response body:
Bad response from Docker engine
```

**Comment by danstarns** [comment]
@darrellwarde  Seems to work on windows just fine 😂 Be keen to see if you get any more error than just that? With your fancy visions would everyone need docker installed?

**Comment by darrellwarde** [comment]
> @darrellwarde Seems to work on windows just fine 😂 Be keen to see if you get any more error than just that? With your fancy visions would everyone need docker installed?

Sadly that's literally all I get... 😞  That is true regarding everyone needing Docker installed, I guess I just have dreams of consistent environments everywhere!

**Comment by danstarns** [comment]
@darrellwarde We should all develop on a raspberry PI job sorted! It would be nice to offer docker for contributors... after all docker is designed to be the consistent environment. Keen to see if it works for @oskarhane

**Pull request closed without merging**
