### PR TITLE
Feat - OGM Select

### PR DESCRIPTION
**Pull request by danstarns**
[Fulfills the RFC](https://github.com/neo4j/graphql/pull/2417), and introduces type safety for the OGM selectionSet - No more string yay!

This is something I put together in my free time and can’t guarantee that I can see this all the way to the end, that’s if the Neo4j GraphQL team would like this to be implemented. Please feel free to make any changes to this PR as you see fit. 

What's todo?

I have implemented what I see as the majority use case for this, Node and Relationship fields, and the following will need attention:

1. Unions and Interfaces
2. Connections
3. Relationship Aggregations

# Checklist

The following requirements should have been met (depending on the changes in the branch):

- [ ] Documentation has been updated
- [ ] TCK tests have been updated
- [ ] Integration tests have been updated
- [ ] Example applications have been updated
- [ ] New files have copyright header
- [ ] CLA (https://neo4j.com/developer/cla/) has been signed

### CODE REVIEW

**Comment by neo4j-team-graphql** [comment]
Made some changes to the GraphQL Toolbox? Or made some changes to the core library perhaps?

Check out your changes at
 https://neo4j-graphql-toolbox-stage-2418.surge.sh

Use for instance a local dbms hosted on [Neo4j Desktop](https://neo4j.com/download/) or a cloud-hosted [Aura Free](https://neo4j.com/cloud/aura-free/) dbms.

**Comment by tbwiss** [comment]
Hi @danstarns! Nice to have you back!!
Thanks for opening this PR and the RFC. We'll check this shortly!

**Comment by darrellwarde** [comment]
Yeeeesssss, great to hear from you @danstarns!!! 👏 I hope you're doing well.

I do have what feels like a slightly ridiculous request for you... Can you sign the CLA? https://neo4j.com/developer/cla/#sign-cla

You are still on the whitelist from when you were with us, but I have been informed that we need a record of the signed CLA in our inbox. Sorry! 😳

**Comment by danstarns** [comment]
@tbwiss @darrellwarde 

Hi. My name is John Doe (john@doe.com, johndoe).
I agree to the terms in the attached Neo4j Contributor License Agreement.

;) Just sent it. Good to hear from you both.

**Comment by darrellwarde** [comment]
I think this is definitely a feature we would like, and we would love to see continued work on it @danstarns! 

We likely won't get time to work on this ourselves for a while (as per usual, library taking higher precedence, and a major release around the corner). However, it is on the roadmap (admittedly in the somewhat distant future) to take a good look at the OGM as a whole and to make it more of a first class citizen along with the library.

**Comment by darrellwarde** [comment]
I'm going to close this for the time being as it's grown a bit stale, but do feel free to reopen this if you want to continue working on this! We will look into features like this later down the line, but right now, we need to focus elsewhere, and want to try and keep our backlog of PRs relatively clear. 🙂

**Comment by neo4j-team-graphql** [comment]
Thanks for the UI updates.

The UI has now been torn down - reopening this PR will republish it.

**Pull request closed without merging**
