### PR TITLE
Combine where statements with roles as moderators, as with allow, bind

### PR DESCRIPTION
**Pull request by rcbevans**
Given the following auth rules:

```
@auth(rules: [
    {
        operations: [READ],
        roles: ["""member"""],
        where: {
            owner: { authId: """$jwt.sub""" },
        }
    },
    {
        operations: [READ],
        roles: ["""admin"""],
    },
])
```

I am trying to express that a member or an admin can perform read operations on the annotated type, but that members can only see nodes where the connected owner node has an authId matching their jwt subject.

However, the generated Cypher for the auth, whilst correctly checking for either member or admin roles, is not composing them with other rules in an appropriate way leading to the following Cypher being executed:

```
MATCH (this:AppConn)
WHERE EXISTS((this)<-[:OWNS_CONNECTION]-(:Person)) AND ALL(owner IN [(this)<-[:OWNS_CONNECTION]-(owner:Person) | owner] WHERE owner.authId IS NOT NULL AND owner.authId = $this_auth_where0_owner_authId)
CALL apoc.util.validate(NOT(ANY(r IN ["member"] WHERE ANY(rr IN $auth.roles WHERE r = rr)) OR ANY(r IN ["admin"] WHERE ANY(rr IN $auth.roles WHERE r = rr))), "@neo4j/graphql/FORBIDDEN", [0])
RETURN this { .id, .name, .description, created_time: apoc.date.convertFormat(toString(this.created), "iso_zoned_date_time", "iso_offset_date_time"), updated_time: apoc.date.convertFormat(toString(this.updated), "iso_zoned_date_time", "iso_offset_date_time"), source_app_user: this.authenticatedUser, user_id:  apoc.cypher.runFirstColumn("MATCH (this)<-[:OWNS_CONNECTION]-(p:Person) RETURN p.authId", {this: this, auth: $auth}, false) } as this
SKIP $this_offset
LIMIT $this_limit
```

The Cypher is always applying the where filter such that admins cannot see everything, rather than combining it with a stronger requirement like roles to scope the filtering.

This change now moderates `where` rules with their co-existent `roles` rules such that the `where` policy for one role will only apply when the `role` policy applies:

```
MATCH (this:AppConn)
WHERE ANY(r IN ["member"] WHERE ANY(rr IN $auth.roles WHERE r = rr)) AND EXISTS((this)<-[:OWNS_CONNECTION]-(:Person)) AND ALL(owner IN [(this)<-[:OWNS_CONNECTION]-(owner:Person) | owner] WHERE owner.authId IS NOT NULL AND owner.authId = $this_auth_where0_owner_authId) OR ANY(r IN ["admin"] WHERE ANY(rr IN $auth.roles WHERE r = rr))
CALL apoc.util.validate(NOT(ANY(r IN ["member"] WHERE ANY(rr IN $auth.roles WHERE r = rr)) OR ANY(r IN ["admin"] WHERE ANY(rr IN $auth.roles WHERE r = rr))), "@neo4j/graphql/FORBIDDEN", [0])
RETURN this { .id, .name, .description, created_time: apoc.date.convertFormat(toString(this.created), "iso_zoned_date_time", "iso_offset_date_time"), updated_time: apoc.date.convertFormat(toString(this.updated), "iso_zoned_date_time", "iso_offset_date_time"), user_id:  apoc.cypher.runFirstColumn("MATCH (this)<-[:OWNS_CONNECTION]-(p:Person) RETURN p.authId", {this: this, auth: $auth}, false) } as this
SKIP $this_offset
LIMIT $this_limit
```

I still perform a check to skip generation of a `WHERE` statement if no rules contain a `where`.

# Description

Please provide a description of the work completed in this branch.

# Issue

Please provide a link to the GitHub issue in which the proposal for this work was discussed. 

It's important that changes are discussed in advance to make sure we choose the right solution and to avoid duplication of effort.

# Checklist

The following requirements should have been met (depending on the changes in the branch):

- [ ] Documentation has been updated
- [ ] TCK tests have been updated
- [ ] Integration tests have been updated
- [ ] Example applications have been updated
- [ ] New files have copyright header
- [x] CLA (https://neo4j.com/developer/cla/) has been signed

### CODE REVIEW

**Comment by rcbevans** [comment]
This is a placeholder PR addressing #482.

I will add/update integration/tck tests when I get the change, but the change itself can be discussed.

**Comment by darrellwarde** [comment]
Thanks for the contribution @rcbevans, we'll get around to looking at it over the coming days. 🙂 

As a side note, you'll see that the CLA Check is failing for you. Despite you signing the CLA, you haven't got your git client configured to commit using the email address associated with your GitHub account (see https://github.com/neo4j/graphql/pull/483/commits where the username on your commit does not link through to your profile). Can you please follow the steps at https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-github-user-account/managing-email-preferences/setting-your-commit-email-address#setting-your-commit-email-address-in-git and then reset and re-commit your changes please?

**Comment by oskarhane** [comment]
Hi! I see that you've signed the CLA, which is great!

But it seems your commits aren't made using the same email address matching your GH user so our CLA check doesn't recognize the committer.
Could I ask you to re-commit your changes with a Git user matching configured to match your GH user?

Sorry for the inconvenience.

**Comment by rcbevans** [comment]
Yeah I think git used my work (panda.ai) GPG key which has the wrong email on there.  I will fix that when I get around to it. I'm also trying to find time to figure out where tests need extending to get that coverage in too.

**Comment by rcbevans** [comment]
Closing this one, reopened a new one based on latest and with the correct committer id

https://github.com/neo4j/graphql/pull/490

**Pull request closed without merging**
