### PR TITLE
Fix typename mutations

### LINKED ISSUE #4583: Error when using the typename filter with mutations
**Describe the bug**
Unexpected error is thrown because typename is treated as a field.

**Type definitions**
```graphql
 interface Production {
                title: String!
                actors: [Actor!]! @declareRelationship
            }

            type Movie implements Production {
                title: String!
                runtime: Int!
                actors: [Actor!]! @relationship(type: "ACTED_IN", direction: IN, properties: "ActedIn")
            }

            type Series implements Production {
                title: String!
                episodeCount: Int!
                actors: [Actor!]! @relationship(type: "ACTED_IN", direction: IN, properties: "StarredIn")
            }

            type ActedIn @relationshipProperties {
                screenTime: Int!
            }


            type StarredIn @relationshipProperties {
                episodeNr: Int!
            }

            type Actor {
                name: String!
                actedIn: [Production!]! @relationship(type: "ACTED_IN", direction: OUT, properties: "ActedIn")
            }
```

**To Reproduce**
1. Run mutation
```graphql
 mutation CreateActors {
        createActors(
              input: {
                name: "My Actor"
                actedIn: {
                  connect: {
                    edge: { screenTime: 10 }
                    where: { node: { title: "some movie", typename_IN: [Movie] } }
                  }
                }
              }
            ) {
              actors {
                name
              }
            }
          }
```
2. Notice error

**Expected behavior**

**Screenshots**

**System (please complete the following information):**

* OS: [e.g. macOS, Windows]
* Version: [e.g. @neo4j/graphql@1.0.0]
* Node.js version: [e.g. 14.16.0]

**Additional context**

### PR DESCRIPTION
**Pull request by MacondoExpress**
# Description

Fix typename filters when used with connect operations.

Closes  #4583 

The following requirements should have been met (depending on the changes in the branch):

- [x] Documentation has been updated
- [x] TCK tests have been updated
- [x] Integration tests have been updated
- [x] Example applications have been updated
- [x] New files have copyright header
- [x] CLA (https://neo4j.com/developer/cla/) has been signed

### CODE REVIEW

**Comment by neo4j-team-graphql** [comment]
Thanks for the Neo4j GraphQL Toolbox updates.

The Neo4j GraphQL Toolbox has now been torn down - reopening this PR will republish it.

**Comment by neo4j-team-graphql** [comment]
# Performance Report

No Performance Changes


<details>
    <summary>Show Full Table</summary>
    
| name | dbHits | old dbHits | time (ms) | old time (ms) | maxRows |
| ---- | ------ | ---------- | --------- | ------------- | ------- |
|  aggregations.TopLevelAggregate | 3404 | 3404 | 35 | 57 | 1134 |
|  aggregations.TopLevelAggregateWithMultipleFields | 6802 | 6802 | 48 | 56 | 1134 |
|  aggregations.NestedAggregation | 16544 | 16544 | 66 | 89 | 2174 |
|  aggregations.AggregationWithWhere | 11970 | 11970 | 37 | 54 | 2174 |
|  aggregations.AggregationWhereWithinNestedRelationships | 22116478 | 22116478 | 2192 | 2379 | 2008534 |
|  aggregations.AggregationWhereWithinNestedConnections | 22116478 | 22116478 | 2284 | 2293 | 2008534 |
|  aggregations.NestedCountFromMovieToActors | 9701 | 9701 | 36 | 40 | 2174 |
|  aggregations.NestedCountFromActorsToMovie | 9928 | 9928 | 31 | 46 | 2174 |
|  aggregations.DeeplyNestedCount | 11062184 | 11062184 | 2944 | 2780 | 2008534 |
|  aggregations.InterfacesAggregations | 6242 | 6242 | 48 | 54 | 2080 |
|  aggregations.InterfacesAggregationsWithTwoFields | 11444 | 11444 | 73 | 86 | 2080 |
|  batch-create.BatchCreate | 4200 | 4200 | 143 | 164 | 600 |
|  batch-create.BatchCreateSmall | 77 | 77 | 51 | 90 | 11 |
|  connect.createAndConnect | 14424 | 14424 | 152 | 171 | 3003 |
|  connections.Connection | 14049 | 14049 | 53 | 67 | 2174 |
|  connections.NestedConnection | 41068 | 41068 | 112 | 147 | 4516 |
|  create.SimpleMutation | 7 | 7 | 49 | 73 | 1 |
|  cypher-directive.TopLevelMutationDirective | 1135 | 1135 | 38 | 24 | 1134 |
|  delete.SimpleDelete | 19401 | 19401 | 195 | 216 | 1040 |
|  delete.NestedDeleteInUpdate | 19165 | 19165 | 174 | 167 | 1183 |
|  2871.NestedRelationshipFilter | 23119 | 23117 | 52 | 62 | 4445 |
|  2925.SingleRelationshipFilter | 6468 | 6468 | 37 | 41 | 1040 |
|  2925.NestedSingleRelationshipFilter | 22891 | 22891 | 68 | 104 | 2174 |
|  2925.SingleRelationshipRequiredFilter | 5201 | 5201 | 34 | 38 | 1040 |
|  2925.NestedSingleRelationshipRequiredFilter | 9361 | 9361 | 50 | 55 | 1040 |
|  query.SimpleQuery | 3121 | 3121 | 21 | 20 | 1040 |
|  query.SimpleQueryWithRelationship | 16129 | 16129 | 44 | 43 | 2174 |
|  query.QueryWhere | 9689 | 9679 | 38 | 36 | 2165 |
|  query.SimpleQueryWithNestedWhere | 9856 | 9846 | 49 | 50 | 2165 |
|  query.Nested | 10095502 | 10095502 | 7092 | 7000 | 2008534 |
|  query.NestedWithFilter | 10074351 | 10074351 | 6692 | 6957 | 2004000 |
|  query.OrFilterOnRelationships | 41948 | 41935 | 147 | 164 | 1595 |
|  query.OrFilterOnRelationshipsAndNested | 35643 | 36050 | 226 | 238 | 1595 |
|  query.QueryWithNestedIn | 13583 | 13715 | 53 | 55 | 1288 |
|  query.NestedConnectionWhere | 9801 | 9801 | 55 | 58 | 2174 |
|  query.DeeplyNestedConnectionWhere | 9981 | 9986 | 107 | 88 | 2174 |
|  query.DeeplyNestedWithRelationshipFilters | 18932 | 18926 | 139 | 153 | 1646 |
|  query.NestedWithRelationshipSingleFilters | 3865 | 3865 | 144 | 172 | 1134 |
|  query.Fulltext | 64 | 64 | 35 | 40 | 16 |
|  query.FulltextWithNestedQuery | 558 | 558 | 39 | 54 | 84 |
|  sorting-and-cypher.TopLevelSortWithCypher | 14059 | 14059 | 43 | 48 | 2174 |
|  sorting-and-cypher.TopLevelConnectionSortWithCypher | 14059 | 14059 | 62 | 69 | 2174 |
|  sorting-and-cypher.TopLevelSortWithCypherWithNested | 14169 | 14185 | 62 | 63 | 2174 |
|  sorting-and-cypher.TopLevelConnectionSortWithCypherWithNested | 14169 | 14185 | 112 | 108 | 2174 |
|  sorting-and-cypher.TopLevelSortWithExpensiveCypher | 14785 | 14591 | 102 | 144 | 2174 |
|  sorting-and-cypher.TopLevelConnectionSortWithExpensiveCypher | 14571 | 14376 | 100 | 145 | 2174 |
|  sorting.SortMultipleTypes | 3498 | 3498 | 78 | 116 | 1040 |
|  sorting.SortMultipleTypesWithCypherWithCypher | 14428 | 14453 | 104 | 138 | 2174 |
|  sorting.SortOnNestedFields | 14049 | 14049 | 41 | 57 | 2174 |
|  sorting.SortDeeplyNestedFields | 43148 | 43148 | 75 | 91 | 4516 |
|  sorting.ConnectionWithSort | 3281 | 3281 | 78 | 95 | 1040 |
|  unions.SimpleUnionQuery | 321 | 321 | 53 | 65 | 35 |
|  unions.SimpleUnionQueryWithMissingFields | 293 | 293 | 57 | 61 | 35 |
|  unions.NestedUnion | 410637 | 410637 | 279 | 248 | 33033 |
|  unions.NestedUnionWithMissingFields | 384611 | 384611 | 272 | 259 | 33033 |
|  update.NestedUpdate | 16143 | 16143 | 108 | 126 | 2002 |

</details>
        
Old Schema Generation: 25.290s
Schema Generation: 25.696s
Old Subgraph Schema Generation: 29.885s
Subgraph Schema Generation: 29.441s

**Review by angrykoala — APPROVED** [review]

**Review by a-alle — COMMENTED** [review]
Looks good to me. I was thinking of 2 extra testing scenarios that might be useful. What do you think?
1. filter containing a logical operator with the typename inside the "sub-filters"
2. nested connect with typename filters at both levels (like in the second test from 4583 file but with Movie.actors being an Interface which would allow another typename filter at the nested level)

**Comment by MacondoExpress** [comment]
@a-alle added more tests!

**Pull request merged**
