### PR TITLE
Relationship properties type

### PR DESCRIPTION
**Pull request by angrykoala**
# Description

Change relationshipProperties to types instead of interfaces

### CODE REVIEW

**Comment by neo4j-team-graphql** [comment]
Made some changes to the Neo4j GraphQL Toolbox? Or made some changes to the core library perhaps?

Check out your changes at https://neo4j-graphql-toolbox-4410.surge.sh

Use for instance a local dbms hosted on [Neo4j Desktop](https://neo4j.com/download/) or a cloud-hosted [Aura Free](https://neo4j.com/cloud/aura-free/) dbms.

**Comment by neo4j-team-graphql** [comment]
# Performance Report

No Performance Changes


<details>
    <summary>Show Full Table</summary>
    
| name | dbHits | old dbHits | time (ms) | old time (ms) | maxRows |
| ---- | ------ | ---------- | --------- | ------------- | ------- |
|  aggregations.TopLevelAggregate | 3404 | 3404 | 32 | 39 | 1134 |
|  aggregations.TopLevelAggregateWithMultipleFields | 6802 | 6802 | 41 | 54 | 1134 |
|  aggregations.NestedAggregation | 16544 | 16544 | 54 | 76 | 2174 |
|  aggregations.AggregationWithWhere | 11970 | 11970 | 42 | 51 | 2174 |
|  aggregations.AggregationWhereWithinNestedRelationships | 22116478 | 22116478 | 2114 | 2185 | 2008534 |
|  aggregations.AggregationWhereWithinNestedConnections | 22116478 | 22116478 | 2148 | 2141 | 2008534 |
|  aggregations.NestedCountFromMovieToActors | 9701 | 9701 | 34 | 36 | 2174 |
|  aggregations.NestedCountFromActorsToMovie | 9928 | 9928 | 30 | 37 | 2174 |
|  aggregations.DeeplyNestedCount | 11062184 | 11062184 | 2850 | 2523 | 2008534 |
|  aggregations.InterfacesAggregations | 6242 | 6242 | 42 | 47 | 2080 |
|  aggregations.InterfacesAggregationsWithTwoFields | 11444 | 11444 | 69 | 91 | 2080 |
|  batch-create.BatchCreate | 4200 | 4200 | 118 | 154 | 600 |
|  batch-create.BatchCreateSmall | 77 | 77 | 45 | 66 | 11 |
|  connect.createAndConnect | 14424 | 14424 | 125 | 156 | 3003 |
|  connections.Connection | 14049 | 14049 | 50 | 68 | 2174 |
|  connections.NestedConnection | 41068 | 41068 | 121 | 132 | 4516 |
|  create.SimpleMutation | 7 | 7 | 47 | 49 | 1 |
|  cypher-directive.TopLevelMutationDirective | 1135 | 1135 | 25 | 23 | 1134 |
|  delete.SimpleDelete | 19401 | 19401 | 221 | 206 | 1040 |
|  delete.NestedDeleteInUpdate | 19165 | 19165 | 154 | 192 | 1183 |
|  2871.NestedRelationshipFilter | 23093 | 23043 | 52 | 59 | 4438 |
|  2925.SingleRelationshipFilter | 6468 | 6468 | 40 | 41 | 1040 |
|  2925.NestedSingleRelationshipFilter | 22891 | 22891 | 70 | 80 | 2174 |
|  2925.SingleRelationshipRequiredFilter | 5201 | 5201 | 32 | 38 | 1040 |
|  2925.NestedSingleRelationshipRequiredFilter | 9361 | 9361 | 44 | 57 | 1040 |
|  query.SimpleQuery | 3121 | 3121 | 18 | 21 | 1040 |
|  query.SimpleQueryWithRelationship | 16129 | 16129 | 41 | 39 | 2174 |
|  query.QueryWhere | 9676 | 9668 | 29 | 44 | 2161 |
|  query.SimpleQueryWithNestedWhere | 9843 | 9835 | 42 | 48 | 2161 |
|  query.Nested | 10095502 | 10095502 | 6972 | 6534 | 2008534 |
|  query.NestedWithFilter | 10074351 | 10074351 | 6820 | 6470 | 2004000 |
|  query.OrFilterOnRelationships | 43019 | 43057 | 129 | 148 | 2031 |
|  query.OrFilterOnRelationshipsAndNested | 37365 | 35991 | 179 | 248 | 2031 |
|  query.QueryWithNestedIn | 13632 | 13252 | 46 | 55 | 1305 |
|  query.NestedConnectionWhere | 9801 | 9801 | 44 | 52 | 2174 |
|  query.DeeplyNestedConnectionWhere | 10006 | 10056 | 64 | 100 | 2174 |
|  query.DeeplyNestedWithRelationshipFilters | 18962 | 18974 | 128 | 165 | 1652 |
|  query.NestedWithRelationshipSingleFilters | 3865 | 3865 | 136 | 179 | 1134 |
|  query.Fulltext | 64 | 64 | 26 | 47 | 16 |
|  query.FulltextWithNestedQuery | 558 | 558 | 50 | 50 | 84 |
|  sorting-and-cypher.TopLevelSortWithCypher | 14059 | 14059 | 41 | 46 | 2174 |
|  sorting-and-cypher.TopLevelConnectionSortWithCypher | 14059 | 14059 | 62 | 66 | 2174 |
|  sorting-and-cypher.TopLevelSortWithCypherWithNested | 14188 | 14137 | 50 | 58 | 2174 |
|  sorting-and-cypher.TopLevelConnectionSortWithCypherWithNested | 14188 | 14137 | 86 | 96 | 2174 |
|  sorting-and-cypher.TopLevelSortWithExpensiveCypher | 14582 | 14401 | 86 | 117 | 2174 |
|  sorting-and-cypher.TopLevelConnectionSortWithExpensiveCypher | 14432 | 14332 | 88 | 102 | 2174 |
|  sorting.SortMultipleTypes | 3498 | 3498 | 68 | 92 | 1040 |
|  sorting.SortMultipleTypesWithCypherWithCypher | 14501 | 14462 | 88 | 101 | 2174 |
|  sorting.SortOnNestedFields | 14049 | 14049 | 38 | 54 | 2174 |
|  sorting.SortDeeplyNestedFields | 43148 | 43148 | 76 | 98 | 4516 |
|  sorting.ConnectionWithSort | 3281 | 3281 | 58 | 68 | 1040 |
|  unions.SimpleUnionQuery | 321 | 321 | 46 | 51 | 35 |
|  unions.SimpleUnionQueryWithMissingFields | 293 | 293 | 43 | 54 | 35 |
|  unions.NestedUnion | 410637 | 410637 | 228 | 244 | 33033 |
|  unions.NestedUnionWithMissingFields | 384611 | 384611 | 224 | 243 | 33033 |
|  update.NestedUpdate | 16143 | 16143 | 100 | 88 | 2002 |

</details>
        
Old Schema Generation: 24.165s
Schema Generation: 24.319s
Old Subgraph Schema Generation: 27.214s
Subgraph Schema Generation: 27.362s

**Review by a-alle — APPROVED** [review]
LGTM! Do we need a changeset?

**Comment by angrykoala** [comment]
It does need a changeset, good spot

**Pull request merged**
