### PR TITLE
changed all occurences of 'neoSchema' to 'neo4jGraphQL' in all files

### PR DESCRIPTION
**Pull request by maieulChevalier**
# Description

I changed all occurences of `neoSchema` to `neo4jgraphql` in all files by using ctrl+shift+f in vsCode.

# Issue

No github issue but we discussed this on discord: https://discord.com/channels/787399249741479977/818578492723036210/937419349508112476. This avoids confusion as neoSchema.schema doesn't really makes sense, and Neo4jGraphQL is more than just an augmented schema, but also generated resolvers, etc.

# Checklist

The following requirements should have been met (depending on the changes in the branch):

- [x] Documentation has been updated
- [x] TCK tests have been updated
- [x] Integration tests have been updated
- [x] Example applications have been updated
- [ ] New files have copyright header
- [x] CLA (https://neo4j.com/developer/cla/) has been signed

### CODE REVIEW

**Comment by neo4j-team-graphql** [comment]
Looks like you've updated the documentation!

Check out your changes at https://neo4j-graphql-docs-898.surge.sh

**Comment by maieulChevalier** [comment]
Just in case this might be an issue, I've seen that `neo4jgraphql` was already being used in some `.adoc` files.

**Comment by danstarns** [comment]
Sorry @maieulChevalier, I'm going to close this one based on how out of date it is. We have discussed this one internally and we actually think that it should be `neo4jGraphQL`:

```diff
const neoSchema = new Neo4jGraphQL()
const neo4jGraphQL = new Neo4jGraphQL()
````

We have some big branches open at the moment so one of us will go through and change this when done! Thank you for taking the time to contribute.

**Comment by maieulChevalier** [comment]
Okay, no problem! Thanks for listening to the community!

**Pull request closed without merging**
