### PR TITLE
remove computed directive

### PR DESCRIPTION
**Pull request by a-alle**
# Description

Removes references of the deprecated `@computed` directive from docs and code. 

## Complexity

Complexity: Low

### CODE REVIEW

**Comment by neo4j-team-graphql** [comment]
# Performance Report

No Performance Changes


<details>
    <summary>Show Full Table</summary>
    
| name | dbHits | old dbHits | time (ms) | old time (ms) | maxRows |
| ---- | ------ | ---------- | --------- | ------------- | ------- |
|  aggregations.TopLevelAggregate | 3403 | 3403 | 32 | 52 | 1134 |
|  aggregations.NestedAggregation | 13514 | 13514 | 108 | 148 | 2174 |
|  aggregations.AggregationWithWhere | 10942 | 10942 | 67 | 106 | 2174 |
|  aggregations.NestedCountFromMovieToActors | 8694 | 8694 | 74 | 167 | 2174 |
|  aggregations.NestedCountFromActorsToMovie | 8900 | 8900 | 58 | 167 | 2174 |
|  aggregations.DeeplyNestedCount | 10054408 | 10054408 | 4076 | 4481 | 2008534 |
|  batch-create.BatchCreate | 3600 | 3600 | 92 | 144 | 600 |
|  connect.createAndConnect | 12419 | 12419 | 278 | 259 | 3003 |
|  connections.Connection | 13042 | 13042 | 134 | 153 | 2174 |
|  connections.NestedConnection | 33883 | 33883 | 113 | 147 | 4516 |
|  connections.ConnectionWithSort | 2277 | 2277 | 57 | 95 | 1040 |
|  connections.ConnectionWithSortAndCypher | 14278 | 14278 | 101 | 147 | 2174 |
|  create.SimpleMutation | 6 | 6 | 33 | 32 | 1 |
|  cypher-directive.TopLevelMutationDirective | 1135 | 1135 | 69 | 59 | 1134 |
|  delete.SimpleDelete | 18361 | 18361 | 279 | 237 | 1040 |
|  delete.NestedDeleteInUpdate | 16779 | 16779 | 257 | 167 | 2040 |
|  query.SimpleQuery | 14120 | 14120 | 100 | 128 | 2174 |
|  query.QueryWhere | 8672 | 8676 | 41 | 59 | 2165 |
|  query.SimpleQueryWithNestedWhere | 8843 | 8847 | 64 | 73 | 2165 |
|  query.Nested | 10084290 | 10084290 | 11148 | 9764 | 2008534 |
|  query.NestedWithFilter | 37172 | 37172 | 134 | 154 | 4511 |
|  query.OrFilterOnRelationships | 36486 | 37181 | 149 | 177 | 1587 |
|  query.OrFilterOnRelationshipsAndNested | 30147 | 31059 | 245 | 290 | 1587 |
|  query.QueryWithNestedIn | 12513 | 12301 | 63 | 84 | 1273 |
|  query.NestedConnectionWhere | 8794 | 8794 | 97 | 79 | 2174 |
|  query.DeeplyNestedConnectionWhere | 8962 | 8838 | 68 | 102 | 2174 |
|  query.DeeplyNestedWithRelationshipFilters | 6251 | 6251 | 113 | 195 | 1134 |
|  query.DeeplyNestedWithRelationshipSingleFilters | 15438 | 15438 | 91 | 117 | 2174 |
|  query.Fulltext | 96 | 96 | 27 | 27 | 16 |
|  query.FulltextWithNestedQuery | 571 | 571 | 44 | 43 | 84 |
|  sorting.SortMultipleTypes | 2493 | 2493 | 63 | 66 | 1040 |
|  sorting.SortMultipleTypesWithCypherWithCypher | 13466 | 13422 | 82 | 137 | 2174 |
|  sorting.SortOnNestedFields | 13042 | 13042 | 71 | 125 | 2174 |
|  sorting.SortDeeplyNestedFields | 38965 | 38965 | 164 | 227 | 4516 |
|  sorting.SortWithTopLevelCypher | 14120 | 14120 | 54 | 72 | 2174 |
|  unions.SimpleUnionQuery | 321 | 321 | 60 | 63 | 35 |
|  unions.SimpleUnionQueryWithMissingFields | 293 | 293 | 56 | 71 | 35 |
|  unions.NestedUnion | 398553 | 398553 | 423 | 368 | 33033 |
|  unions.NestedUnionWithMissingFields | 372527 | 372527 | 287 | 348 | 33033 |
|  update.NestedUpdate | 2119 | 2119 | 51 | 41 | 1040 |

</details>
        
Old Schema Generation: 28.751s
Schema Generation: 27.248s

**Review by darrellwarde — APPROVED** [review]
Nice!

**Comment by darrellwarde** [comment]
Ohhhh nooooo, not nice, add a changeset 🙃

**Comment by neo4j-team-graphql** [comment]
# Performance Report

No Performance Changes


<details>
    <summary>Show Full Table</summary>
    
| name | dbHits | old dbHits | time (ms) | old time (ms) | maxRows |
| ---- | ------ | ---------- | --------- | ------------- | ------- |
|  aggregations.TopLevelAggregate | 3403 | 3403 | 36 | 43 | 1134 |
|  aggregations.NestedAggregation | 13514 | 13514 | 94 | 119 | 2174 |
|  aggregations.AggregationWithWhere | 10942 | 10942 | 72 | 90 | 2174 |
|  aggregations.NestedCountFromMovieToActors | 8694 | 8694 | 54 | 91 | 2174 |
|  aggregations.NestedCountFromActorsToMovie | 8900 | 8900 | 73 | 92 | 2174 |
|  aggregations.DeeplyNestedCount | 10054408 | 10054408 | 4404 | 5274 | 2008534 |
|  batch-create.BatchCreate | 3600 | 3600 | 92 | 143 | 600 |
|  connect.createAndConnect | 12419 | 12419 | 242 | 361 | 3003 |
|  connections.Connection | 13042 | 13042 | 150 | 170 | 2174 |
|  connections.NestedConnection | 33883 | 33883 | 112 | 129 | 4516 |
|  connections.ConnectionWithSort | 2277 | 2277 | 63 | 77 | 1040 |
|  connections.ConnectionWithSortAndCypher | 14278 | 14278 | 98 | 133 | 2174 |
|  create.SimpleMutation | 6 | 6 | 35 | 45 | 1 |
|  cypher-directive.TopLevelMutationDirective | 1135 | 1135 | 26 | 111 | 1134 |
|  delete.SimpleDelete | 18361 | 18361 | 329 | 272 | 1040 |
|  delete.NestedDeleteInUpdate | 16779 | 16779 | 148 | 200 | 2040 |
|  query.SimpleQuery | 14120 | 14120 | 135 | 121 | 2174 |
|  query.QueryWhere | 8668 | 8664 | 40 | 46 | 2163 |
|  query.SimpleQueryWithNestedWhere | 8839 | 8835 | 48 | 57 | 2163 |
|  query.Nested | 10084290 | 10084290 | 10240 | 10206 | 2008534 |
|  query.NestedWithFilter | 37172 | 37172 | 178 | 187 | 4511 |
|  query.OrFilterOnRelationships | 37333 | 35447 | 186 | 206 | 2142 |
|  query.OrFilterOnRelationshipsAndNested | 31619 | 29335 | 206 | 313 | 2142 |
|  query.QueryWithNestedIn | 12271 | 12193 | 63 | 60 | 1192 |
|  query.NestedConnectionWhere | 8794 | 8794 | 52 | 61 | 2174 |
|  query.DeeplyNestedConnectionWhere | 8989 | 8888 | 69 | 110 | 2174 |
|  query.DeeplyNestedWithRelationshipFilters | 6251 | 6251 | 128 | 163 | 1134 |
|  query.DeeplyNestedWithRelationshipSingleFilters | 15438 | 15438 | 92 | 159 | 2174 |
|  query.Fulltext | 96 | 96 | 30 | 59 | 16 |
|  query.FulltextWithNestedQuery | 571 | 571 | 41 | 64 | 84 |
|  sorting.SortMultipleTypes | 2493 | 2493 | 62 | 84 | 1040 |
|  sorting.SortMultipleTypesWithCypherWithCypher | 13441 | 13430 | 89 | 111 | 2174 |
|  sorting.SortOnNestedFields | 13042 | 13042 | 64 | 96 | 2174 |
|  sorting.SortDeeplyNestedFields | 38965 | 38965 | 179 | 175 | 4516 |
|  sorting.SortWithTopLevelCypher | 14120 | 14120 | 66 | 55 | 2174 |
|  unions.SimpleUnionQuery | 321 | 321 | 146 | 59 | 35 |
|  unions.SimpleUnionQueryWithMissingFields | 293 | 293 | 70 | 58 | 35 |
|  unions.NestedUnion | 398553 | 398553 | 300 | 340 | 33033 |
|  unions.NestedUnionWithMissingFields | 372527 | 372527 | 300 | 305 | 33033 |
|  update.NestedUpdate | 2119 | 2119 | 52 | 57 | 1040 |

</details>
        
Old Schema Generation: 28.456s
Schema Generation: 29.019s

**Review by darrellwarde — APPROVED** [review]
LGTM!

**Review by angrykoala — APPROVED** [review]

**Pull request merged**
