### PR TITLE
Feature: Ability to query with distinct values

### PR DESCRIPTION
**Pull request by morningcloud**
# Description

This PR is created to include a new boolean attribute `distinct` under the augmented schema `{node.name}Options` to support fetching unique values of node properties (fetching queries with distinct values).

For example, this query:
```
query {
   movies(options: { distinct: true }) {
      title
   }
}
```

Would be translated to Cypher as:
``` 
MATCH (this:Movie)
RETURN DISTINCT this { .title } as this
```
And the following query:
```
query {
   movies {
      title
      genres(options:{distinct: true, limit:2})
   }
}
```

Would be translated to Cypher as:
``` 
MATCH (this:Movie)
RETURN this { .title, genres: apoc.coll.toSet([ (this)-[:HAS_GENRE]->(this_genres:Genre)   | this_genres { .name } ])[..2] } as this
LIMIT $this_limit
```

Appreciate noting that this is my first contribution. I made sure to follow all the guidelines and include as many test cases as I could think of. Would appreciate your review and highlight any concerns to be addressed if any.

# Issue

Addressing Issue #779

# Checklist

The following requirements should have been met (depending on the changes in the branch):

- [x] Documentation has been updated
- [x] TCK tests have been updated
- [x] Integration tests have been updated
- [x] New files have copyright header
- [x] CLA (https://neo4j.com/developer/cla/) has been signed

### CODE REVIEW

**Comment by darrellwarde** [comment]
Hey @morningcloud, I don't actually see the CLA agreement that you sent us, can you confirm that you've followed the steps at https://neo4j.com/developer/cla/#sign-cla? Thanks!

**Comment by morningcloud** [comment]
Hey @darrellwarde, yes I followed the steps in the link and sent the email yesterday. I resent it again today from the same email my github account is linked to.

**Comment by morningcloud** [comment]
Hi @darrellwarde were you able to see the CLA agreement I sent last week?

**Comment by neo4j-team-graphql** [comment]
Looks like you've updated the documentation!

Check out your changes at https://neo4j-graphql-docs-800.surge.sh

**Comment by morningcloud** [comment]
@neo4j-team-graphql I see the workflow has failed due to eslint errors, from looking at the error messages they don't seem to be from the files that I have updated, I saw the same error is there in another PR initiated close to my PR request. Appreciate your advice on what need to be done to fix this as I tried merging with upstream and still getting the eslint errors.

**Comment by darrellwarde** [comment]
> @neo4j-team-graphql I see the workflow has failed due to eslint errors, from looking at the error messages they don't seem to be from the files that I have updated, I saw the same error is there in another PR initiated close to my PR request. Appreciate your advice on what need to be done to fix this as I tried merging with upstream and still getting the eslint errors.

Hey @morningcloud - if it's files which you've not updated yourself then feel free to ignore and we also will. This shouldn't be the case however, because Reviewdog which we use only comments on updated files. Thanks for the work here, and sorry we're being a little slow to review.

**Comment by morningcloud** [comment]
I probably should not have done this but I merged the latest dev branch from upstream to my forked branch. This started a chain reaction of merging issues and additional test files to refactor. I should have tackled all such errors now.

Hopefully these merge actions are not making the review more difficult!

**Comment by morningcloud** [comment]
@darrellwarde @neo4j-team-graphql I would appreciate your support in reviewing this request, I keep getting emails on failed workflow run but the status of the pull request here shows that it is pending approval. I already ran the test scripts locally and it went through without any errors. As this is my first change attempt, I am keen to know if there is any correction needed and if this pull request is suitable to be taken up for merge :)

**Comment by darrellwarde** [comment]
> @darrellwarde @neo4j-team-graphql I would appreciate your support in reviewing this request, I keep getting emails on failed workflow run but the status of the pull request here shows that it is pending approval. I already ran the test scripts locally and it went through without any errors. As this is my first change attempt, I am keen to know if there is any correction needed and if this pull request is suitable to be taken up for merge

@morningcloud, I'm afraid we've been super busy getting ready for the next release and just haven't had time to go through this in detail. Rest assured that we will get around to it, we just need a bit of time!

**Comment by darrellwarde** [comment]
Hey @morningcloud, super sorry for the slow response here. I've just posted a comment in #779 regarding the implementation of this feature, if you'd like to take a look. 🙂

**Pull request closed without merging**
