### PR TITLE
Remove `Neo4jDatabaseInfo` from the public context

### PR DESCRIPTION
**Pull request by darrellwarde**
# Description

Removes `Neo4jDatabaseInfo` from the public API. Exposing this field in the context was only ever added to overcome the already incredibly unlikely scenario of users switching between different database versions in the context. Removing in an attempt to fully clean up our public surface. If a need for this ever arises again, we should implement a proper solution which caches DBMS URIs and associates them with a version, so that we can deal with different versions ourselves.

## Complexity

Complexity: Low

### CODE REVIEW

**Comment by neo4j-team-graphql** [comment]
Looks like you've updated the documentation!

Check out your changes at https://neo4j-graphql-docs-3630.surge.sh

**Comment by neo4j-team-graphql** [comment]
Made some changes to the Neo4j GraphQL Toolbox? Or made some changes to the core library perhaps?

Check out your changes at https://neo4j-graphql-toolbox-3630.surge.sh

Use for instance a local dbms hosted on [Neo4j Desktop](https://neo4j.com/download/) or a cloud-hosted [Aura Free](https://neo4j.com/cloud/aura-free/) dbms.

**Comment by neo4j-team-graphql** [comment]
# Performance Report

No Performance Changes


<details>
    <summary>Show Full Table</summary>
    
| name | dbHits | old dbHits | time (ms) | old time (ms) | maxRows |
| ---- | ------ | ---------- | --------- | ------------- | ------- |
|  aggregations.TopLevelAggregate | 3403 | 3403 | 40 | 66 | 1134 |
|  aggregations.NestedAggregation | 16553 | 16553 | 139 | 135 | 2174 |
|  aggregations.AggregationWithWhere | 11979 | 11979 | 56 | 76 | 2174 |
|  aggregations.AggregationWhereWithinNestedRelationships | 22116987 | 22116987 | 4655 | 4585 | 2008534 |
|  aggregations.AggregationWhereWithinNestedConnections | 22116987 | 22116987 | 3934 | 4099 | 2008534 |
|  aggregations.NestedCountFromMovieToActors | 9734 | 9734 | 57 | 62 | 2174 |
|  aggregations.NestedCountFromActorsToMovie | 9937 | 9937 | 67 | 62 | 2174 |
|  aggregations.DeeplyNestedCount | 13070329 | 13070333 | 6031 | 6363 | 2008534 |
|  batch-create.BatchCreate | 4200 | 4200 | 159 | 213 | 600 |
|  batch-create.BatchCreateSmall | 77 | 77 | 82 | 117 | 11 |
|  connect.createAndConnect | 14424 | 14424 | 248 | 248 | 3003 |
|  connections.Connection | 14082 | 14082 | 100 | 96 | 2174 |
|  connections.NestedConnection | 45466 | 45470 | 141 | 197 | 4516 |
|  connections.ConnectionWithSort | 3284 | 3284 | 80 | 106 | 1040 |
|  connections.ConnectionWithSortAndCypher | 16325 | 16325 | 129 | 133 | 2174 |
|  create.SimpleMutation | 7 | 7 | 71 | 130 | 1 |
|  cypher-directive.TopLevelMutationDirective | 1135 | 1135 | 71 | 34 | 1134 |
|  delete.SimpleDelete | 19401 | 19401 | 377 | 373 | 1040 |
|  delete.NestedDeleteInUpdate | 19542 | 19542 | 256 | 358 | 1183 |
|  2925.SingleRelationshipFilter | 6468 | 6468 | 49 | 73 | 1040 |
|  2925.NestedSingleRelationshipFilter | 22900 | 22900 | 101 | 178 | 2174 |
|  2925.SingleRelationshipRequiredFilter | 5201 | 5201 | 54 | 57 | 1040 |
|  2925.NestedSingleRelationshipRequiredFilter | 9361 | 9361 | 69 | 84 | 1040 |
|  query.SimpleQuery | 3121 | 3121 | 26 | 32 | 1040 |
|  query.SimpleQueryWithRelationship | 16162 | 16162 | 63 | 64 | 2174 |
|  query.QueryWhere | 9708 | 9711 | 43 | 57 | 2165 |
|  query.SimpleQueryWithNestedWhere | 9886 | 9889 | 77 | 96 | 2165 |
|  query.Nested | 10096041 | 10096041 | 12330 | 12107 | 2008534 |
|  query.NestedWithFilter | 10074401 | 10074401 | 11990 | 11810 | 2004000 |
|  query.OrFilterOnRelationships | 42181 | 42154 | 299 | 322 | 1544 |
|  query.OrFilterOnRelationshipsAndNested | 36303 | 36057 | 287 | 317 | 1544 |
|  query.QueryWithNestedIn | 14006 | 13934 | 71 | 75 | 1419 |
|  query.NestedConnectionWhere | 9834 | 9834 | 82 | 81 | 2174 |
|  query.DeeplyNestedConnectionWhere | 9849 | 9851 | 99 | 130 | 2174 |
|  query.DeeplyNestedWithRelationshipFilters | 19044 | 19002 | 174 | 269 | 1564 |
|  query.NestedWithRelationshipSingleFilters | 3881 | 3881 | 217 | 499 | 1134 |
|  query.Fulltext | 80 | 80 | 38 | 45 | 16 |
|  query.FulltextWithNestedQuery | 587 | 587 | 54 | 72 | 84 |
|  sorting.SortMultipleTypes | 3515 | 3515 | 82 | 91 | 1040 |
|  sorting.SortMultipleTypesWithCypherWithCypher | 14490 | 14464 | 131 | 137 | 2174 |
|  sorting.SortOnNestedFields | 14082 | 14082 | 64 | 80 | 2174 |
|  sorting.SortDeeplyNestedFields | 43198 | 43198 | 128 | 136 | 4516 |
|  sorting.SortWithTopLevelCypher | 16162 | 16162 | 95 | 70 | 2174 |
|  unions.SimpleUnionQuery | 321 | 321 | 76 | 96 | 35 |
|  unions.SimpleUnionQueryWithMissingFields | 293 | 293 | 77 | 92 | 35 |
|  unions.NestedUnion | 410637 | 410637 | 358 | 350 | 33033 |
|  unions.NestedUnionWithMissingFields | 384611 | 384611 | 336 | 403 | 33033 |
|  update.NestedUpdate | 16143 | 16143 | 175 | 191 | 2002 |

</details>
        
Old Schema Generation: 58.219s
Schema Generation: 59.235s
Old Subgraph Schema Generation: 1:12.348 (m:ss.mmm)
Subgraph Schema Generation: 1:14.602 (m:ss.mmm)

**Review by MacondoExpress — APPROVED** [review]

**Comment by MacondoExpress** [comment]
LGTM, before merging it, there is a test to fix which still using the old export!

**Pull request merged**
