### PR TITLE
Project cypher field if needed for sort on a root connection query (fixes #1364)

### LINKED ISSUE #1364: Sort Broken on Cypher Field When Querying Root Connections
**Describe the bug**

Sort no longer works with connections when using a cypher field since the projection happens *after* the sort is applied.  I'll work on a fix at some point.

Given the schema: 

```graphql
type Organization {
  id: ID! @id
  fundraises: [Opportunity!]! @relationship(type: "IS_COMPANY_IN", direction: OUT)
  roundsRaised: Int! @cypher(statement: """
  MATCH (this)-[:IS_COMPANY_IN]->(opp:Opportunity)
  RETURN count(opp)
  """)
}

type Opportunity {
  id: ID! @id
  investedCompanies: [Organization!]! @relationship(type: "IS_COMPANY_IN", direction: IN)
}
```

Run the following query:

```graphql

query MyQuery($sort: [OrganizationSort], $where: OrganizationWhere!) {
  organizationsConnection(
    first: 20
    sort: [{ roundsRaised: DESC }]
  ) {
    edges {
      cursor
      node {
        id
        roundsRaised
      }
    }
  }
}

```

And it will produce cypher like the following from an actual query I ran:

```
CALL {
MATCH (this:Organization)
WITH COLLECT(this) as edges
WITH edges, size(edges) as totalCount
UNWIND edges as this
RETURN this, totalCount
# <--- Sort happens here
ORDER BY this.roundsRaised DESC
LIMIT $this_limit
}
# <--- But projection happens here
WITH COLLECT({ node: this { .name, roundsRaised:  apoc.cypher.runFirstColumn("MATCH (this)-[:IS_COMPANY_IN]->(opp:Opportunity)
RETURN count(opp)", {this: this, auth: $auth}, false) } }) as edges, totalCount
RETURN { edges: edges, totalCount: totalCount } as this
```

Result is that sort is broken.

* OS: Mac
* Version: 3.1.0
* Node.js version: 14.x

### PR DESCRIPTION
**Pull request by litewarp**
# Description

If a cypher field is needed for sorting on a root connection, we project that field before sorting.  

Closes:

- #1364

# Checklist

The following requirements should have been met (depending on the changes in the branch):

- [ ] Documentation has been updated
- [X] TCK tests have been updated
- [ ] Integration tests have been updated
- [ ] Example applications have been updated
- [X] New files have copyright header
- [X] CLA (https://neo4j.com/developer/cla/) has been signed

### CODE REVIEW

**Comment by darrellwarde** [comment]
Hey @litewarp, thanks for this fix! Is it worth adding some integration tests to show that the sorting works in these different scenarios?

**Comment by litewarp** [comment]
@darrellwarde Probably but it's 3am here and I'm not sure when I'll be able to get to it again. And since it's a hotfix, it probably needs to go out sooner or later. Could use an assist here.

**Comment by litewarp** [comment]
@darrellwarde Thanks!

Yeah, it turns out my cypher is not as strong as I'd like it to be. Refactor translate-read a bit to clean it up and fixed the cypher problems. It should pass now.

**Comment by litewarp** [comment]
Hey @darrellwarde was there a reason this didn't make it into 3.2.1?

**Comment by darrellwarde** [comment]
> Hey @darrellwarde was there a reason this didn't make it into 3.2.1?

To be very honest with you, I completely forgot that I hadn't merged it! Sorry @litewarp, leave it with me!

**Comment by darrellwarde** [comment]
Released in 3.2.2 @litewarp, sorry again about that! 🙏

**Pull request merged**
