### PR TITLE
Fix optional cookie

### PR DESCRIPTION
**Pull request by gasp**
# Description

prevent app crash with errors `Cannot read property 'token' of undefined`

# Issue

1. start the neo-push server
`yarn workspace neo-push-server start`
2. query anything

### what happens

it triggers an error `Cannot read property 'token' of undefined`
token-property-error

### expected result

it should run smoothly

itworksfine

# Checklist

The following requirements should have been met (depending on the changes in the branch):

- [ ] Documentation has been updated
- [ ] TCK tests have been updated
- [ ] Integration tests have been updated
- [ ] Example applications have been updated
- [ ] New files have copyright header
- [x] CLA (https://neo4j.com/developer/cla/) has been signed

### CODE REVIEW

**Comment by darrellwarde** [comment]
We'll just need to add to the CLA allowlist and then we'll take a look at this. 🙂 Thanks for the contribution!

**Review by oskarhane — APPROVED** [review]
LGTM

**Comment by kristjanmik** [comment]
@OskarDamkjaer I stumbled into this bug on the 2.0.0-alpha.x release (published 21 days ago) in npm. This patch has been back-ported into the 2.0.0 branch but is still missing from the npm registry :)

**Comment by OskarDamkjaer** [comment]
@kristjanmik Is it me you seek of @oskarhane ? :)

**Comment by kristjanmik** [comment]
Yes, I'm summoning all the Oskars, sorry about that. I'm indeed calling on the power of @oskarhane.

**Pull request merged**
