### PR TITLE
Optimize getNeo4jResolveTree for big schema

### PR DESCRIPTION
**Pull request by angrykoala**
# Description
This PR optimises the code in getNeo4jResolveTree when as the schema size increases, as discusses in #3303 

The results on performance for simple queries with ~3000 types on schema:
| Query | Requests Fullfilled | Request Duration P(90) | DB Query Time P(90) | Max Event Loop Delay (ms) | Memory Usage (MB) | getNeo4jResolveTree avg time (ms) |
| ------------ | ------------------- | ---------------------- | ------------------- | ------------------------- | ----------------- | --------------------------------- |
| Simple Query (unoptimized)         | 6915                | 8.11s                  | 513ms               | 4000                      | ~1900             | 5.54                              |
| Simple Query (optimized)           | 61860 (+794%)       | 387ms (+95%)           | 27ms*               | 18                        | ~2500*            | 0.016                             |

* DB Query Time has not been optimised, but the overall improvement in event loop delay is affecting the measurements
* Max Memory usage has increased, this is likely not a problem, and caused by the less garbage collection as cloning is not as common after the optimization

This optimization does not have a significant impact on complex queries with small schemas, performance issues regarding complex queries are probably elsewhere

### CODE REVIEW

**Comment by neo4j-team-graphql** [comment]
Made some changes to the Neo4j GraphQL Toolbox? Or made some changes to the core library perhaps?

Check out your changes at https://neo4j-graphql-toolbox-3309.surge.sh

Use for instance a local dbms hosted on [Neo4j Desktop](https://neo4j.com/download/) or a cloud-hosted [Aura Free](https://neo4j.com/cloud/aura-free/) dbms.

**Review by mjfwebb — APPROVED** [review]
Great stuff! :tada:

**Comment by neo4j-team-graphql** [comment]
# Performance Report

No Performance Changes


<details>
    <summary>Show Full Table</summary>
    
| name | dbHits | old dbHits | time (ms) | old time (ms) | maxRows |
| ---- | ------ | ---------- | --------- | ------------- | ------- |
|  aggregations.TopLevelAggregate | 3403 | 3403 | 37 | 66 | 1134 |
|  aggregations.NestedAggregation | 16553 | 16553 | 77 | 101 | 2174 |
|  aggregations.AggregationWithWhere | 11979 | 11979 | 44 | 77 | 2174 |
|  aggregations.AggregationWhereWithinNestedRelationships | 22116987 | 22116987 | 3031 | 3243 | 2008534 |
|  aggregations.AggregationWhereWithinNestedConnections | 22116987 | 22116987 | 2802 | 2957 | 2008534 |
|  aggregations.NestedCountFromMovieToActors | 9734 | 9734 | 39 | 47 | 2174 |
|  aggregations.NestedCountFromActorsToMovie | 9937 | 9937 | 37 | 57 | 2174 |
|  aggregations.DeeplyNestedCount | 13070333 | 13070331 | 4489 | 4197 | 2008534 |
|  batch-create.BatchCreate | 4200 | 4200 | 139 | 144 | 600 |
|  batch-create.BatchCreateSmall | 77 | 77 | 94 | 71 | 11 |
|  connect.createAndConnect | 14424 | 14424 | 160 | 231 | 3003 |
|  connections.Connection | 14082 | 14082 | 81 | 62 | 2174 |
|  connections.NestedConnection | 45466 | 45472 | 123 | 129 | 4516 |
|  connections.ConnectionWithSort | 3284 | 3284 | 73 | 84 | 1040 |
|  connections.ConnectionWithSortAndCypher | 3284 | 3284 | 173 | 300 | 1040 |
|  create.SimpleMutation | 7 | 7 | 69 | 72 | 1 |
|  cypher-directive.TopLevelCypherDirective | 122100 | 122100 | 601 | 612 | 12241 |
|  cypher-directive.TopLevelCypherDirectiveWithColumnName | 153617 | 153617 | 176 | 205 | 12241 |
|  delete.SimpleDelete | 19401 | 19401 | 243 | 343 | 1040 |
|  delete.NestedDeleteInUpdate | 23202 | 23202 | 171 | 326 | 2040 |
|  2925.SingleRelationshipFilter | 6468 | 6468 | 110 | 46 | 1040 |
|  2925.NestedSingleRelationshipFilter | 22900 | 22900 | 99 | 96 | 2174 |
|  2925.SingleRelationshipRequiredFilter | 3450 | 3450 | 26 | 28 | 1134 |
|  2925.NestedSingleRelationshipRequiredFilter | 9383 | 9383 | 46 | 51 | 1040 |
|  query.SimpleQuery | 16162 | 16162 | 43 | 57 | 2174 |
|  query.QueryWhere | 9712 | 9718 | 33 | 43 | 2165 |
|  query.SimpleQueryWithNestedWhere | 9890 | 9896 | 49 | 61 | 2165 |
|  query.Nested | 10096041 | 10096041 | 10040 | 10301 | 2008534 |
|  query.NestedWithFilter | 10074401 | 10074401 | 10329 | 9638 | 2004000 |
|  query.OrFilterOnRelationships | 40859 | 42467 | 169 | 213 | 1179 |
|  query.OrFilterOnRelationshipsAndNested | 34313 | 36337 | 228 | 258 | 1179 |
|  query.QueryWithNestedIn | 13214 | 13443 | 54 | 63 | 1154 |
|  query.NestedConnectionWhere | 9834 | 9834 | 69 | 59 | 2174 |
|  query.DeeplyNestedConnectionWhere | 10003 | 9891 | 77 | 95 | 2174 |
|  query.DeeplyNestedWithRelationshipFilters | 19242 | 19104 | 122 | 168 | 1630 |
|  query.NestedWithRelationshipSingleFilters | 3732 | 3732 | 286 | 223 | 1134 |
|  query.Fulltext | 80 | 80 | 55 | 33 | 16 |
|  query.FulltextWithNestedQuery | 587 | 587 | 57 | 57 | 84 |
|  sorting.SortMultipleTypes | 3515 | 3515 | 76 | 85 | 1040 |
|  sorting.SortMultipleTypesWithCypherWithCypher | 1449 | 1404 | 179 | 244 | 1040 |
|  sorting.SortOnNestedFields | 14082 | 14082 | 49 | 65 | 2174 |
|  sorting.SortDeeplyNestedFields | 43198 | 43198 | 84 | 137 | 4516 |
|  sorting.SortWithTopLevelCypher | 3121 | 3121 | 105 | 315 | 1040 |
|  unions.SimpleUnionQuery | 321 | 321 | 60 | 98 | 35 |
|  unions.SimpleUnionQueryWithMissingFields | 293 | 293 | 61 | 69 | 35 |
|  unions.NestedUnion | 410637 | 410637 | 303 | 324 | 33033 |
|  unions.NestedUnionWithMissingFields | 384611 | 384611 | 313 | 328 | 33033 |
|  update.NestedUpdate | 16143 | 16143 | 118 | 109 | 2002 |

</details>
        
Old Schema Generation: 36.547s
Schema Generation: 36.561s
Old Subgraph Schema Generation: 49.250s
Subgraph Schema Generation: 49.204s

**Comment by amborle** [comment]
Amazing stuff!

**Pull request merged**
