### PR TITLE
feat: resolve fields on unions returned by top-level custom cypher

### PR DESCRIPTION
**Pull request by rcbevans**
Resolve fields on unions returned from top-level cypher statements.

This is a port of @john2094's change for the same feature onto the latest master branch.

# Description

In the cypher resolver, check if the return from the cypher field is a union, and if so, generate the projection appropriately

# Issue

#487 

# Checklist

The following requirements should have been met (depending on the changes in the branch):

- [ ] Documentation has been updated
- [ ] TCK tests have been updated
- [ ] Integration tests have been updated
- [ ] Example applications have been updated
- [ ] New files have copyright header
- [x] CLA (https://neo4j.com/developer/cla/) has been signed

### CODE REVIEW

**Comment by rcbevans** [comment]
This code is lifted and shifted from the previous PR onto master.

Looking at the code though, it seems like this implementation is executing the cypher query once for each type in the union since `addSecurityAndConnection` is called within the foreach loop.

I am also taking a look at the cypherField projection in [create-project-and-params](https://github.com/neo4j/graphql/blob/d51fb4c112d7e6efe96207f1c8155c08b0d2a3f8/packages/graphql/src/translate/create-projection-and-params.ts#L171).  I'm new to Neo4j/Cypher and so I'm not 100% sure what the generated cypher should look like.

**Comment by darrellwarde** [comment]
Thanks @rcbevans, we'll take a look when we're back from the weekend - have a good one! 🙂

**Comment by rcbevans** [comment]
Just looked at the code being executed and it is indeed performing the APOC call twice within an outer union.

```
call {


                WITH apoc.cypher.runFirstColumn("<statement>", {auth: $auth, input: $input}, false) as x
                UNWIND x as this
                WITH this
            

            match(thisnode:Account)

            where thisnode=this or apoc.map.merge(properties(thisnode), { __resolveType: 'Account' })=properties(this)\n" +
            return thisnode { __resolveType: "Account", .id, ... } as this
union

                WITH apoc.cypher.runFirstColumn("<statement>", {auth: $auth, input: $input}, false) as x
                UNWIND x as this
                WITH this
            

            match(thisnode:Page)

            where thisnode=this or apoc.map.merge(properties(thisnode), { __resolveType: 'Page' })=properties(this)\n" +
            return thisnode { __resolveType: "Page", .id, ... } as this
}
with this AS this
            RETURN this
```

**Comment by rcbevans** [comment]
I have an alternate PR which tackles resolving both top level cypher, as well as cypherFields, #495.

That implementation does a single apoc call then uses the same pattern as in relational fields to match the union types and and project.

**Comment by darrellwarde** [comment]
> I have an alternate PR which tackles resolving both top level cypher, as well as cypherFields, #495.
> 
> That implementation does a single apoc call then uses the same pattern as in relational fields to match the union types and and project.

So are you suggesting that we close this and review only #495 instead? 🙂 Thanks for all of this work!

**Comment by rcbevans** [comment]
@darrellwarde yes I think so.  #495 is a more efficient implementation

**Pull request closed without merging**
