### PR TITLE
RFC-028: Surface executed cypher

### PR DESCRIPTION
**Pull request by tbwiss**
This is still WIP!

Show the executed cypher and its params for each query.

### CODE REVIEW

**Comment by helenesanche** [comment]
**Idea for this feature**
The GraphQL Toolbox in its current shape is a great tool for first time users to explore the library features, explore queries, debugging, but once people have gained a better understanding and confidence in using the library they might not need the Toolbox anymore. 
By adding a way to surface the cypher translation of their GraphQL queries we can _**retain**_ **_more users_** who might be interested in understanding why some queries are slow, and by giving them additional information we can create a user journey where a developer uses the Toolbox to debug a problem or a slow query, then they reach out to us on Discord by sending a link to the Toolbox. This was we can make the Toolbox part of the developer experience of Neo4j GraphQL community.

**Comment by helenesanche** [comment]
This looks great to me, thanks @tbwiss ! 
One addition I suggest is to show a one-time pop-up to users who login after we've implemented the feature and haven't previously login, so we can educate them on the new changes. 
The pop-up can say something along the lines of:
`"You can see the cypher executed by enabling this new feature in Settings" `

**Comment by tbwiss** [comment]
@helenesanche Having a thought about this one-time pop-up. We can leverage Canny (which we already have in place), or more precise the [Canny changelog widget](https://developers.canny.io/install/changelog), for that. The integration of that changelog widget with the Toolbox should not be challenging and since we already use Canny we can leverage it for one more task.
The content of the changelog widget can be drafted, published and removed via the Canny UI and without having to change any code in the Toolbox. Needless to say it also helps for future "releases" and "feature notifications".
What do you think?

**Comment by tbwiss** [comment]
Closing this as we need to re-think the approach here. The new approach will be handled in a new RFC

**Pull request closed without merging**
