### PR TITLE
docs: fix typo in api reference

### PR DESCRIPTION
**Pull request by AlexxNica**
`consraints` -> `constraints`

### CODE REVIEW

**Review by darrellwarde — APPROVED** [review]
Thanks @AlexxNica!

**Comment by darrellwarde** [comment]
Actually @AlexxNica, just checked and looks like you may not have signed our CLA. Can you make sure that's done so we can get this merged? Thanks! https://neo4j.com/developer/cla/#sign-cla

**Comment by AlexxNica** [comment]
@darrellwarde Hey, sorry about that! Just did it! 😄

**Comment by neo4j-team-graphql** [comment]
Looks like you've updated the documentation!

Check out your changes at https://neo4j-graphql-docs-1275.surge.sh

**Pull request merged**
