### PR TITLE
Implement Interface field directives validation rule

### PR DESCRIPTION
**Pull request by a-alle**
# Description

Only a subset of the field directives are applicable to Interface fields: schema config directives, private and relationship (temporarily until the alternative is implemented). 
This PR introduces a validation rule that enforces this - under the experimental flag as it's highly breaking.

## Complexity

Complexity: Low

# Issue

> **Note**
>
>  Please link to the GitHub issue(s) in which the proposal for this work was discussed
>  
>  To link to multiple issues, use full syntax for each, for example `Closes #1, closes #2, closes #3`

Closes 

# Checklist

The following requirements should have been met (depending on the changes in the branch):

- [ ] Documentation has been updated
- [ ] TCK tests have been updated
- [ ] Integration tests have been updated
- [ ] Example applications have been updated
- [ ] New files have copyright header
- [ ] CLA (https://neo4j.com/developer/cla/) has been signed

### CODE REVIEW

**Comment by neo4j-team-graphql** [comment]
Made some changes to the Neo4j GraphQL Toolbox? Or made some changes to the core library perhaps?

Check out your changes at https://neo4j-graphql-toolbox-4219.surge.sh

Use for instance a local dbms hosted on [Neo4j Desktop](https://neo4j.com/download/) or a cloud-hosted [Aura Free](https://neo4j.com/cloud/aura-free/) dbms.

**Comment by neo4j-team-graphql** [comment]
# Performance Report

No Performance Changes


<details>
    <summary>Show Full Table</summary>
    
| name | dbHits | old dbHits | time (ms) | old time (ms) | maxRows |
| ---- | ------ | ---------- | --------- | ------------- | ------- |
|  aggregations.TopLevelAggregate | 3403 | 3403 | 48 | 72 | 1134 |
|  aggregations.NestedAggregation | 16553 | 16553 | 120 | 143 | 2174 |
|  aggregations.AggregationWithWhere | 11979 | 11979 | 62 | 83 | 2174 |
|  aggregations.AggregationWhereWithinNestedRelationships | 22116987 | 22116987 | 4134 | 4470 | 2008534 |
|  aggregations.AggregationWhereWithinNestedConnections | 22116987 | 22116987 | 3597 | 4106 | 2008534 |
|  aggregations.NestedCountFromMovieToActors | 9734 | 9734 | 48 | 64 | 2174 |
|  aggregations.NestedCountFromActorsToMovie | 9937 | 9937 | 69 | 63 | 2174 |
|  aggregations.DeeplyNestedCount | 11062443 | 11062443 | 6508 | 6314 | 2008534 |
|  batch-create.BatchCreate | 4200 | 4200 | 164 | 211 | 600 |
|  batch-create.BatchCreateSmall | 77 | 77 | 76 | 121 | 11 |
|  connect.createAndConnect | 14424 | 14424 | 214 | 316 | 3003 |
|  connections.Connection | 14082 | 14082 | 71 | 110 | 2174 |
|  connections.NestedConnection | 41118 | 41118 | 135 | 151 | 4516 |
|  create.SimpleMutation | 7 | 7 | 85 | 84 | 1 |
|  cypher-directive.TopLevelMutationDirective | 1135 | 1135 | 91 | 44 | 1134 |
|  delete.SimpleDelete | 19401 | 19401 | 319 | 319 | 1040 |
|  delete.NestedDeleteInUpdate | 19198 | 19198 | 262 | 282 | 1183 |
|  2871.NestedRelationshipFilter | 23180 | 23143 | 82 | 97 | 4447 |
|  2925.SingleRelationshipFilter | 6468 | 6468 | 58 | 65 | 1040 |
|  2925.NestedSingleRelationshipFilter | 22900 | 22900 | 111 | 155 | 2174 |
|  2925.SingleRelationshipRequiredFilter | 5201 | 5201 | 52 | 63 | 1040 |
|  2925.NestedSingleRelationshipRequiredFilter | 9361 | 9361 | 78 | 115 | 1040 |
|  query.SimpleQuery | 3121 | 3121 | 29 | 34 | 1040 |
|  query.SimpleQueryWithRelationship | 16162 | 16162 | 57 | 66 | 2174 |
|  query.QueryWhere | 9726 | 9702 | 51 | 86 | 2171 |
|  query.SimpleQueryWithNestedWhere | 9904 | 9880 | 69 | 81 | 2171 |
|  query.Nested | 10096041 | 10096041 | 13410 | 12556 | 2008534 |
|  query.NestedWithFilter | 10074401 | 10074401 | 13602 | 12525 | 2004000 |
|  query.OrFilterOnRelationships | 41595 | 44019 | 233 | 308 | 1511 |
|  query.OrFilterOnRelationshipsAndNested | 35945 | 36905 | 283 | 329 | 1511 |
|  query.QueryWithNestedIn | 14171 | 13487 | 77 | 86 | 1475 |
|  query.NestedConnectionWhere | 9834 | 9834 | 76 | 85 | 2174 |
|  query.DeeplyNestedConnectionWhere | 9961 | 9998 | 108 | 154 | 2174 |
|  query.DeeplyNestedWithRelationshipFilters | 19146 | 19248 | 222 | 273 | 1602 |
|  query.NestedWithRelationshipSingleFilters | 3881 | 3881 | 282 | 343 | 1134 |
|  query.Fulltext | 80 | 80 | 44 | 58 | 16 |
|  query.FulltextWithNestedQuery | 587 | 587 | 59 | 67 | 84 |
|  sorting-and-cypher.TopLevelSortWithCypher | 14092 | 14092 | 121 | 78 | 2174 |
|  sorting-and-cypher.TopLevelConnectionSortWithCypher | 14092 | 14092 | 99 | 97 | 2174 |
|  sorting-and-cypher.TopLevelSortWithCypherWithNested | 14238 | 14245 | 88 | 100 | 2174 |
|  sorting-and-cypher.TopLevelConnectionSortWithCypherWithNested | 14238 | 14245 | 118 | 137 | 2174 |
|  sorting-and-cypher.TopLevelSortWithExpensiveCypher | 15025 | 14956 | 160 | 168 | 2174 |
|  sorting-and-cypher.TopLevelConnectionSortWithExpensiveCypher | 14516 | 14555 | 146 | 165 | 2174 |
|  sorting.SortMultipleTypes | 3515 | 3515 | 99 | 104 | 1040 |
|  sorting.SortMultipleTypesWithCypherWithCypher | 14449 | 14459 | 130 | 132 | 2174 |
|  sorting.SortOnNestedFields | 14082 | 14082 | 62 | 70 | 2174 |
|  sorting.SortDeeplyNestedFields | 43198 | 43198 | 120 | 130 | 4516 |
|  sorting.ConnectionWithSort | 3284 | 3284 | 86 | 92 | 1040 |
|  unions.SimpleUnionQuery | 321 | 321 | 83 | 170 | 35 |
|  unions.SimpleUnionQueryWithMissingFields | 293 | 293 | 85 | 150 | 35 |
|  unions.NestedUnion | 410637 | 410637 | 515 | 463 | 33033 |
|  unions.NestedUnionWithMissingFields | 384611 | 384611 | 364 | 362 | 33033 |
|  update.NestedUpdate | 16143 | 16143 | 133 | 184 | 2002 |

</details>
        
Old Schema Generation: 59.916s
Schema Generation: 1:00.141 (m:ss.mmm)
Old Subgraph Schema Generation: 1:19.937 (m:ss.mmm)
Subgraph Schema Generation: 1:19.184 (m:ss.mmm)

**Review by MacondoExpress — APPROVED** [review]
Nice!

**Comment by angrykoala** [comment]
The performance tests have flagged a regression. Is this a false positive or has something changed?

**Pull request merged**
