### PR TITLE
Experimental support of validation schema

### PR DESCRIPTION
**Pull request by a-alle**
# Description

> **Note**
> 
> Please provide a description of the work completed in this PR below

## Complexity

> **Note**
>
> Please provide an estimated complexity of this PR of either Low, Medium or High

Complexity:

# Issue

> **Note**
>
>  Please link to the GitHub issue(s) in which the proposal for this work was discussed
>  
>  To link to multiple issues, use full syntax for each, for example `Closes #1, closes #2, closes #3`

Closes 

# Checklist

The following requirements should have been met (depending on the changes in the branch):

- [ ] Documentation has been updated
- [ ] TCK tests have been updated
- [ ] Integration tests have been updated
- [ ] Example applications have been updated
- [ ] New files have copyright header
- [ ] CLA (https://neo4j.com/developer/cla/) has been signed

### CODE REVIEW

**Comment by neo4j-team-graphql** [comment]
Looks like you've updated the documentation!

Check out your changes at https://neo4j-graphql-docs-2987.surge.sh

**Comment by neo4j-team-graphql** [comment]
Made some changes to the GraphQL Toolbox? Or made some changes to the core library perhaps?

Check out your changes at https://neo4j-graphql-toolbox-stage-2987.surge.sh

Use for instance a local dbms hosted on [Neo4j Desktop](https://neo4j.com/download/) or a cloud-hosted [Aura Free](https://neo4j.com/cloud/aura-free/) dbms.

**Comment by neo4j-team-graphql** [comment]
# Performance Report

No Performance Changes


<details>
    <summary>Show Full Table</summary>
    
| name | dbHits | old dbHits | time (ms) | old time (ms) | maxRows |
| ---- | ------ | ---------- | --------- | ------------- | ------- |
|  aggregations.TopLevelAggregate | 3403 | 3403 | 39 | 46 | 1134 |
|  aggregations.NestedAggregation | 13514 | 13514 | 93 | 132 | 2174 |
|  aggregations.AggregationWithWhere | 10942 | 10942 | 107 | 90 | 2174 |
|  aggregations.AggregationWhereWithinNestedRelationships | 20101954 | 20101954 | 3192 | 3393 | 2008534 |
|  aggregations.AggregationWhereWithinNestedConnections | 20101954 | 20101954 | 2979 | 3124 | 2008534 |
|  aggregations.NestedCountFromMovieToActors | 8694 | 8694 | 63 | 73 | 2174 |
|  aggregations.NestedCountFromActorsToMovie | 8900 | 8900 | 72 | 76 | 2174 |
|  aggregations.DeeplyNestedCount | 12062308 | 12062292 | 4981 | 5424 | 2008534 |
|  batch-create.BatchCreate | 3600 | 3600 | 113 | 121 | 600 |
|  connect.createAndConnect | 12419 | 12419 | 408 | 316 | 3003 |
|  connections.Connection | 13042 | 13042 | 107 | 263 | 2174 |
|  connections.NestedConnection | 38231 | 38231 | 116 | 135 | 4516 |
|  connections.ConnectionWithSort | 2277 | 2277 | 63 | 95 | 1040 |
|  connections.ConnectionWithSortAndCypher | 14278 | 14278 | 97 | 127 | 2174 |
|  create.SimpleMutation | 6 | 6 | 32 | 42 | 1 |
|  cypher-directive.TopLevelMutationDirective | 1135 | 1135 | 37 | 61 | 1134 |
|  delete.SimpleDelete | 18361 | 18361 | 262 | 259 | 1040 |
|  delete.NestedDeleteInUpdate | 16779 | 16779 | 221 | 209 | 2040 |
|  query.SimpleQuery | 14120 | 14120 | 191 | 147 | 2174 |
|  query.QueryWhere | 8670 | 8666 | 42 | 43 | 2164 |
|  query.SimpleQueryWithNestedWhere | 8841 | 8837 | 88 | 60 | 2164 |
|  query.Nested | 10084290 | 10084290 | 10805 | 10582 | 2008534 |
|  query.NestedWithFilter | 37172 | 37172 | 111 | 152 | 4511 |
|  query.OrFilterOnRelationships | 34664 | 35209 | 171 | 186 | 1256 |
|  query.OrFilterOnRelationshipsAndNested | 28329 | 28872 | 209 | 267 | 1256 |
|  query.QueryWithNestedIn | 12300 | 12305 | 59 | 103 | 1203 |
|  query.NestedConnectionWhere | 8794 | 8794 | 55 | 165 | 2174 |
|  query.DeeplyNestedConnectionWhere | 8844 | 8859 | 78 | 180 | 2174 |
|  query.DeeplyNestedWithRelationshipFilters | 6251 | 6251 | 121 | 226 | 1134 |
|  query.NestedWithRelationshipSingleFilters | 3021189 | 3021189 | 633 | 705 | 1003942 |
|  query.Fulltext | 96 | 96 | 27 | 33 | 16 |
|  query.FulltextWithNestedQuery | 571 | 571 | 42 | 48 | 84 |
|  sorting.SortMultipleTypes | 2493 | 2493 | 64 | 82 | 1040 |
|  sorting.SortMultipleTypesWithCypherWithCypher | 13490 | 13488 | 167 | 128 | 2174 |
|  sorting.SortOnNestedFields | 13042 | 13042 | 202 | 92 | 2174 |
|  sorting.SortDeeplyNestedFields | 38965 | 38965 | 113 | 139 | 4516 |
|  sorting.SortWithTopLevelCypher | 14120 | 14120 | 52 | 60 | 2174 |
|  unions.SimpleUnionQuery | 321 | 321 | 61 | 70 | 35 |
|  unions.SimpleUnionQueryWithMissingFields | 293 | 293 | 60 | 68 | 35 |
|  unions.NestedUnion | 398553 | 398553 | 321 | 641 | 33033 |
|  unions.NestedUnionWithMissingFields | 372527 | 372527 | 311 | 341 | 33033 |
|  update.NestedUpdate | 2119 | 2119 | 43 | 63 | 1040 |

</details>
        
Old Schema Generation: 35.654s
Schema Generation: 1:47.081 (m:ss.mmm)

**Comment by MacondoExpress** [comment]
Yes!

**Pull request closed without merging**
