### PR TITLE
Refactor: Use Subqueries

### PR DESCRIPTION
**Pull request by dmoree**
# Description

Refactor codebase to use subqueries where appropriate. Reduces code complexity and can perhaps more efficiently plan queries. For `query` fields (`read`), subqueries are projected before final return statement. For `mutation` fields, projection will work the same and any creation of nodes or relationships should probably be placed inside a [unit subquery](https://neo4j.com/docs/cypher-manual/current/clauses/call-subquery/#subquery-unit)

### Todo
- [x] Relationship fields
- [x] Connection fields
- [ ] Cypher fields - Top level
- [ ] Cypher fields - Field level (see #984)
- [ ] Unit subqueries in mutations

### CODE REVIEW

**Comment by darrellwarde** [comment]
👀 This is a big and important piece of work that we had been meaning to look at!!!

> * [x]  Relationship fields
> * [x]  Connection fields
> * [ ]  Cypher fields - Top level
> * [ ]  Cypher fields - Field level (see [Split: `@cypher` into `@computed` and `@related` #984](https://github.com/neo4j/graphql/pull/984))
> * [ ]  Unit subqueries in mutations

Regarding this checklist, wherever possible, could these please be in separate PRs? 🙏 Thanks for this contribution, excited to see this work!!

**Comment by dmoree** [comment]
@angrykoala Sorry for not getting back sooner. I plan on moving forward with this, but I think I will hold off for a little bit as it touches a lot of the codebase.

**Comment by dmoree** [comment]
@angrykoala Sorry for not getting back sooner. I plan on moving forward with this, but I think I will hold off for a little bit as it touches a lot of the codebase.

**Comment by angrykoala** [comment]
No worries @dmoree 
Let me know if there is something I can help with this

**Comment by angrykoala** [comment]
Closed in favour of #1918 and #1971

**Pull request closed without merging**
