### PR TITLE
Ensure that label checks are performed against parameters

### PR DESCRIPTION
**Pull request by darrellwarde**
# Description

Ensure that label checks in Cypher are performed against parameters.

## Complexity

Complexity: Low

### CODE REVIEW

**Comment by neo4j-team-graphql** [comment]
Made some changes to the Neo4j GraphQL Toolbox? Or made some changes to the core library perhaps?

Check out your changes at https://neo4j-graphql-toolbox-3603.surge.sh

Use for instance a local dbms hosted on [Neo4j Desktop](https://neo4j.com/download/) or a cloud-hosted [Aura Free](https://neo4j.com/cloud/aura-free/) dbms.

**Comment by neo4j-team-graphql** [comment]
# Performance Report

No Performance Changes


<details>
    <summary>Show Full Table</summary>
    
| name | dbHits | old dbHits | time (ms) | old time (ms) | maxRows |
| ---- | ------ | ---------- | --------- | ------------- | ------- |
|  aggregations.TopLevelAggregate | 3403 | 3403 | 52 | 69 | 1134 |
|  aggregations.NestedAggregation | 16553 | 16553 | 99 | 152 | 2174 |
|  aggregations.AggregationWithWhere | 11979 | 11979 | 59 | 87 | 2174 |
|  aggregations.AggregationWhereWithinNestedRelationships | 22116987 | 22116987 | 4823 | 4201 | 2008534 |
|  aggregations.AggregationWhereWithinNestedConnections | 22116987 | 22116987 | 4216 | 4092 | 2008534 |
|  aggregations.NestedCountFromMovieToActors | 9734 | 9734 | 62 | 61 | 2174 |
|  aggregations.NestedCountFromActorsToMovie | 9937 | 9937 | 55 | 72 | 2174 |
|  aggregations.DeeplyNestedCount | 13070329 | 13070331 | 6393 | 6548 | 2008534 |
|  batch-create.BatchCreate | 4200 | 4200 | 232 | 215 | 600 |
|  batch-create.BatchCreateSmall | 77 | 77 | 107 | 155 | 11 |
|  connect.createAndConnect | 14424 | 14424 | 207 | 241 | 3003 |
|  connections.Connection | 14082 | 14082 | 78 | 209 | 2174 |
|  connections.NestedConnection | 45472 | 45472 | 148 | 266 | 4516 |
|  connections.ConnectionWithSort | 3284 | 3284 | 82 | 135 | 1040 |
|  connections.ConnectionWithSortAndCypher | 3284 | 3284 | 319 | 470 | 1040 |
|  create.SimpleMutation | 7 | 7 | 84 | 107 | 1 |
|  cypher-directive.TopLevelCypherDirective | 122100 | 122100 | 743 | 827 | 12241 |
|  cypher-directive.TopLevelCypherDirectiveWithColumnName | 153617 | 153617 | 236 | 237 | 12241 |
|  delete.SimpleDelete | 19401 | 19401 | 489 | 386 | 1040 |
|  delete.NestedDeleteInUpdate | 23546 | 23546 | 357 | 272 | 2040 |
|  2925.SingleRelationshipFilter | 6468 | 6468 | 66 | 208 | 1040 |
|  2925.NestedSingleRelationshipFilter | 22900 | 22900 | 109 | 258 | 2174 |
|  2925.SingleRelationshipRequiredFilter | 5201 | 5201 | 50 | 60 | 1040 |
|  2925.NestedSingleRelationshipRequiredFilter | 9361 | 9361 | 72 | 86 | 1040 |
|  query.SimpleQuery | 3121 | 3121 | 27 | 46 | 1040 |
|  query.SimpleQueryWithRelationship | 16162 | 16162 | 61 | 78 | 2174 |
|  query.QueryWhere | 9718 | 9721 | 52 | 52 | 2168 |
|  query.SimpleQueryWithNestedWhere | 9896 | 9899 | 73 | 74 | 2168 |
|  query.Nested | 10096041 | 10096041 | 13461 | 12561 | 2008534 |
|  query.NestedWithFilter | 10074401 | 10074401 | 13101 | 13047 | 2004000 |
|  query.OrFilterOnRelationships | 42105 | 42805 | 270 | 285 | 1521 |
|  query.OrFilterOnRelationshipsAndNested | 36222 | 36697 | 288 | 357 | 1521 |
|  query.QueryWithNestedIn | 13783 | 13952 | 80 | 93 | 1346 |
|  query.NestedConnectionWhere | 9834 | 9834 | 81 | 96 | 2174 |
|  query.DeeplyNestedConnectionWhere | 9834 | 9834 | 102 | 118 | 2174 |
|  query.DeeplyNestedWithRelationshipFilters | 19050 | 18996 | 201 | 255 | 1564 |
|  query.NestedWithRelationshipSingleFilters | 3881 | 3881 | 389 | 606 | 1134 |
|  query.Fulltext | 80 | 80 | 63 | 41 | 16 |
|  query.FulltextWithNestedQuery | 587 | 587 | 70 | 79 | 84 |
|  sorting.SortMultipleTypes | 3515 | 3515 | 87 | 95 | 1040 |
|  sorting.SortMultipleTypesWithCypherWithCypher | 1455 | 1422 | 255 | 431 | 1040 |
|  sorting.SortOnNestedFields | 14082 | 14082 | 62 | 84 | 2174 |
|  sorting.SortDeeplyNestedFields | 43198 | 43198 | 134 | 153 | 4516 |
|  sorting.SortWithTopLevelCypher | 3121 | 3121 | 193 | 373 | 1040 |
|  unions.SimpleUnionQuery | 321 | 321 | 79 | 91 | 35 |
|  unions.SimpleUnionQueryWithMissingFields | 293 | 293 | 84 | 86 | 35 |
|  unions.NestedUnion | 410637 | 410637 | 340 | 363 | 33033 |
|  unions.NestedUnionWithMissingFields | 384611 | 384611 | 338 | 377 | 33033 |
|  update.NestedUpdate | 16143 | 16143 | 153 | 182 | 2002 |

</details>
        
Old Schema Generation: 1:01.399 (m:ss.mmm)
Schema Generation: 1:03.180 (m:ss.mmm)
Old Subgraph Schema Generation: 1:14.275 (m:ss.mmm)
Subgraph Schema Generation: 1:18.739 (m:ss.mmm)

**Review by MacondoExpress — COMMENTED** [review]
LGTM!

**Review by Liam-Doodson — APPROVED** [review]
LGTM!

**Pull request merged**
