### PR TITLE
Feat: #293 Add support for ANY and ALL in auth rules

### PR DESCRIPTION
**Pull request by rcbevans**
This change is a contribution to resolve an immediate need, and #293.

Add the ability to explicitly specify ANY or ALL in auth rules immediately preceding a relation field to allow overriding the ANY or ALL which is generated in the output cypher statement.

The ANY or ALL only overrides the relation immediately following.

For example given the schema:

```graphql
type Group {
    id: ID
    name: String
    members: [User] @relationship(type: "MEMBER_OF", direction: IN)
}

extend type Group
    @auth(
        rules: [
            {
                operations: [READ, UPDATE, DELETE, CONNECT, DISCONNECT]
                where: { ANY: { members: { id: "$jwt.sub" } } }
            }
        ]
    )

type User {
    id: ID
    name: String
    groups: [Group] @relationship(type: "MEMBER_OF", direction: OUT)
    posts: [Post] @relationship(type: "HAS_POST", direction: OUT)
    content: [Search] @relationship(type: "HAS_POST", direction: OUT) # something to test unions
}
```

the query

```graphql
{
    groups {
        id
        members {
            id
        }
    }
}

```

will generate the query

```cypher
MATCH (this:Group) WHERE EXISTS((this)<-[:MEMBER_OF]-(:User)) AND ANY(members IN [(this)<-[:MEMBER_OF]-(members:User) | members] WHERE members.id IS NOT NULL AND members.id = $this_auth_where0_ANY_members_id) RETURN this { .id, members: [ (this)<-[:MEMBER_OF]-(this_members:User) WHERE this_members.id IS NOT NULL AND this_members.id = $this_members_auth_where0_id | this_members { .id } ] } as this
```

allowing the return of any groups with a member User with id matching the $jwt.sub.

# Description

Please provide a description of the work completed in this branch.

# Issue

Please provide a link to the GitHub issue in which the proposal for this work was discussed. 

It's important that changes are discussed in advance to make sure we choose the right solution and to avoid duplication of effort.

# Checklist

The following requirements should have been met (depending on the changes in the branch):

- [x] Documentation has been updated
- [x] TCK tests have been updated
- [x] Integration tests have been updated
- [x] Example applications have been updated
- [x] New files have copyright header
- [x] CLA (https://neo4j.com/developer/cla/) has been signed

### CODE REVIEW

**Comment by danstarns** [comment]
Hey @rcbevans, thank you for your contribution. It makes sense to allow users to specify this. 

Please could you add integration tests for this? 

How does this work with nested rules? IE: 

```
where: { ANY: { group: { members: { id: "$jwt.sub" } } } }
```

**Comment by rcbevans** [comment]
> Hey @rcbevans, thank you for your contribution. It makes sense to allow users to specify this.
> 
> Please could you add integration tests for this?
> 
> How does this work with nested rules? IE:
> 
> ```
> where: { ANY: { group: { ANY: { members: { id: "$jwt.sub" } } } } }
> ```

I will take a look and try and figure out integration tests.

In terms of behavior, the ANY/ALL specifier overrides the predicate used for exactly one relational edge immediately following it.

So you need to specify an ANY modifier before any relational edge where you want it.  So in your example, it'll allow the nodes where `any` group has `any` member which match the jwt subject.

If you were to remove the second ANY, it would default to the preexisting predicate based on the auth `kind`, which for `where` is `ALL`.

I wanted to maintain backward compatibility, but allow the additional flexibility for those who need it.  For symmetry, you can also explicitly use `ALL` as well as `ANY`.

**Comment by rcbevans** [comment]
I have updated the unit, tck, and integration tests, as well as documentation.

**Comment by rcbevans** [comment]
It also seems like it would be nice to support `NOT` as a modifier.

**Comment by dmoree** [comment]
@rcbevans `ANY` and `ALL` are list predicates. Could you not achieve a `NOT` modifier by expanding the predicate list to include each of the cypher list predicates `{ANY,ALL,NONE,SINGLE}`. This would be a simple addition to this PR.

`NOT ANY` would translate to `NONE`
`NOT ALL` could translate to `SINGLE` (Perhaps `NOT ALL` is more like "some" than "single")

**Comment by neo4j-team-graphql** [comment]
Looks like you've updated the documentation!

Check out your changes at https://neo4j-graphql-docs-469.surge.sh

**Comment by darrellwarde** [comment]
Hey @rcbevans, we did have a bit of a chat about this internally, and we have slight concerns about how this differs to the `where` arguments of the generated schema (i.e. the ones used in your queries/mutations). Even though we don't expose a method of achieving `ANY`/`ALL` on relationships fields there, we do expose it for scalar list fields using `_INCLUDES` and `_NOT_INCLUDES`, and ideally that is what we would do here to keep things consistent. So for the example which you gave:

```graphql
extend type Group
    @auth(
        rules: [
            {
                operations: [READ, UPDATE, DELETE, CONNECT, DISCONNECT]
                where: { ANY: { members: { id: "$jwt.sub" } } }
            }
        ]
    )
```

This would instead be:

```graphql
extend type Group
    @auth(
        rules: [
            {
                operations: [READ, UPDATE, DELETE, CONNECT, DISCONNECT]
                where: { members_INCLUDES: { id: "$jwt.sub" } } 
            }
        ]
    )
```

This will guarantee a consistent developer experience when both designing your API and using your API, and it will also potentially allow for easier use of common code to generate Cypher clauses in future. Thoughts on this?

**Comment by rcbevans** [comment]
So rather than prefixing with a modifier, instead use a postfix to the name which adjusts the semantics?

Presumably no postfix would carry the current `ALL()` semantics, `_INCLUDES` would be `SOME()`, `_NOT_INCLUDES` would be `NOT(SOME())`.  Would `_NOT` translate to `NOT(ALL())`?

I think that design makes sense, given the stimilarity to other parts of the API, and it's simpler to extend vs modifiers to the recursive projection builder which have to carry additional state.

**Comment by rcbevans** [comment]
As an aside, I could see it being useful to support where clauses checking for NULL/NOT NULL, which I don't think is currently possible, do you have any ideas how that could be supported? It seems it would have to be implemented via a special value rather than key modifier

```
where: { caseSealedDate: NULL }
```

Or

```
where: { publishedDate: ANY }
```

Currently the first part of the generated where check is a check for NOT NULL, so to support this the code would have to look ahead at the value being null and emit the appropriate filter.

**Comment by darrellwarde** [comment]
> So rather than prefixing with a modifier, instead use a postfix to the name which adjusts the semantics?
> 
> Presumably no postfix would carry the current `ALL()` semantics, `_INCLUDES` would be `SOME()`, `_NOT_INCLUDES` would be `NOT(SOME())`. Would `_NOT` translate to `NOT(ALL())`?
> 
> I think that design makes sense, given the stimilarity to other parts of the API, and it's simpler to extend vs modifiers to the recursive projection builder which have to carry additional state.

I'm assuming by `SOME` you mean `ANY`? I _believe_ the mapping should be:

- No postfix = `ALL()`
- `_NOT` = `NOT(ALL())
- `_INCLUDES` = `ANY()`
- `_NOT_INCLUDES` = `NOT(ANY())`

> As an aside, I could see it being useful to support where clauses checking for NULL/NOT NULL, which I don't think is currently possible, do you have any ideas how that could be supported? It seems it would have to be implemented via a special value rather than key modifier
> 
> ```
> where: { caseSealedDate: NULL }
> ```
> 
> Or
> 
> ```
> where: { publishedDate: ANY }
> ```
> 
> Currently the first part of the generated where check is a check for NOT NULL, so to support this the code would have to look ahead at the value being null and emit the appropriate filter.

So in the `where` clauses of the actual generated APIs, the checks you've described above would be achieved with:

```
where: { caseSealedDate: null }
```

And:

```
where: { publishedDate_NOT: null }
```

Noting the lowercase `null` there, as to me capitalisation suggests an enum.

**Comment by rcbevans** [comment]
I think that makes sense.  I'll take a look at how much will be involved to get that implemented.

**Comment by rcbevans** [comment]
Closing this PR as the alternate design has been implemented in #500

**Pull request closed without merging**
