### PR TITLE
Chore: Remove unused code

### PR DESCRIPTION
**Pull request by MacondoExpress**
This PR removes unused code, in particular, create-projection-and-params, and its dependencies are no longer used as all projections are produced by the new translation layer.

### CODE REVIEW

**Comment by neo4j-team-graphql** [comment]
Thanks for the Neo4j GraphQL Toolbox updates.

The Neo4j GraphQL Toolbox has now been torn down - reopening this PR will republish it.

**Review by angrykoala — DISMISSED** [review]
Good job on this

**Comment by angrykoala** [comment]
Maybe we could consider merging this into 5.0.0 to reduce conflicts maybe?

**Comment by MacondoExpress** [comment]
> Good job on this

Thank you! I already checked the merge conflicts it currently has few minor conflicts on the 5.0.0 branch.

**Pull request merged**
