### PR TITLE
initial refactor to CypherBuilder of Projections

### PR DESCRIPTION
**Pull request by MacondoExpress**
# Introduce Cypher Builder usage on Projection

This PR wants to introduce the usage of Cypher Builder mainly on the `createProjectionAndParams` and related code.
As a result of the migration, the `chainStr` is no longer during the projection.
As the variable generated for the `@cypher` field is now an independent `Cypher.Variable`, a new `cypherFieldAliasMap` argument is introduced to keep the reference between the `Cypher.Variable` and the related GraphQL field, the reference is then only used to support sorting by `@cypher` field.
The translation of the create mutations no longer use the `hack` of the `REPLACE_ME` variable but instead, the projection is generated independently for each variable, this overhead, will eventually be removed by the IR work or eventually by the migration to the `unwind-create` structure.
e a description of the work completed in this PR below

## Complexity

Complexity: High

# Checklist

The following requirements should have been met (depending on the changes in the branch):

- [x] Documentation has been updated
- [x] TCK tests have been updated
- [x] Integration tests have been updated
- [x] Example applications have been updated
- [x] New files have copyright header
- [x] CLA (https://neo4j.com/developer/cla/) has been signed

### CODE REVIEW

**Comment by neo4j-team-graphql** [comment]
Made some changes to the GraphQL Toolbox? Or made some changes to the core library perhaps?

Check out your changes at https://neo4j-graphql-toolbox-stage-2882.surge.sh

Use for instance a local dbms hosted on [Neo4j Desktop](https://neo4j.com/download/) or a cloud-hosted [Aura Free](https://neo4j.com/cloud/aura-free/) dbms.

**Comment by neo4j-team-graphql** [comment]
# Performance Report

No Performance Changes


<details>
    <summary>Show Full Table</summary>
    
| name | dbHits | old dbHits | time (ms) | old time (ms) | maxRows |
| ---- | ------ | ---------- | --------- | ------------- | ------- |
|  aggregations.TopLevelAggregate | 3403 | 3403 | 33 | 59 | 1134 |
|  aggregations.NestedAggregation | 13514 | 13514 | 103 | 144 | 2174 |
|  aggregations.AggregationWithWhere | 10942 | 10942 | 62 | 162 | 2174 |
|  aggregations.AggregationWhereWithinNestedRelationships | 20101954 | 20101954 | 3351 | 3431 | 2008534 |
|  aggregations.AggregationWhereWithinNestedConnections | 20101954 | 20101954 | 3018 | 2976 | 2008534 |
|  aggregations.NestedCountFromMovieToActors | 8694 | 8694 | 52 | 57 | 2174 |
|  aggregations.NestedCountFromActorsToMovie | 8900 | 8900 | 71 | 78 | 2174 |
|  aggregations.DeeplyNestedCount | 10054408 | 10054408 | 4553 | 5143 | 2008534 |
|  batch-create.BatchCreate | 3600 | 3600 | 91 | 110 | 600 |
|  connect.createAndConnect | 12419 | 12419 | 251 | 250 | 3003 |
|  connections.Connection | 13042 | 13042 | 100 | 127 | 2174 |
|  connections.NestedConnection | 33883 | 33883 | 117 | 135 | 4516 |
|  connections.ConnectionWithSort | 2277 | 2277 | 58 | 69 | 1040 |
|  connections.ConnectionWithSortAndCypher | 2277 | 2277 | 180 | 325 | 1040 |
|  create.SimpleMutation | 6 | 6 | 31 | 43 | 1 |
|  cypher-directive.TopLevelCypherDirective | 99525 | 99525 | 917 | 761 | 10168 |
|  cypher-directive.TopLevelCypherDirectiveWithColumnName | 127992 | 127994 | 258 | 298 | 10168 |
|  delete.SimpleDelete | 18361 | 18361 | 217 | 258 | 1040 |
|  delete.NestedDeleteInUpdate | 17123 | 17123 | 131 | 232 | 2040 |
|  query.SimpleQuery | 14120 | 14120 | 163 | 171 | 2174 |
|  query.QueryWhere | 8662 | 8665 | 53 | 45 | 2161 |
|  query.SimpleQueryWithNestedWhere | 8833 | 8836 | 58 | 78 | 2161 |
|  query.Nested | 10084290 | 10084290 | 10389 | 10049 | 2008534 |
|  query.NestedWithFilter | 37172 | 37172 | 117 | 132 | 4511 |
|  query.OrFilterOnRelationships | 37401 | 35849 | 163 | 197 | 2156 |
|  query.OrFilterOnRelationshipsAndNested | 31265 | 29589 | 207 | 224 | 2156 |
|  query.QueryWithNestedIn | 12273 | 12430 | 52 | 68 | 1192 |
|  query.NestedConnectionWhere | 8794 | 8794 | 52 | 63 | 2174 |
|  query.DeeplyNestedConnectionWhere | 9009 | 8841 | 76 | 237 | 2174 |
|  query.DeeplyNestedWithRelationshipFilters | 6251 | 6251 | 127 | 317 | 1134 |
|  query.NestedWithRelationshipSingleFilters | 3021189 | 3021189 | 626 | 713 | 1003942 |
|  query.Fulltext | 96 | 96 | 29 | 36 | 16 |
|  query.FulltextWithNestedQuery | 571 | 571 | 41 | 46 | 84 |
|  sorting.SortMultipleTypes | 2493 | 2493 | 62 | 70 | 1040 |
|  sorting.SortMultipleTypesWithCypherWithCypher | 1408 | 1404 | 172 | 290 | 1040 |
|  sorting.SortOnNestedFields | 13042 | 13042 | 60 | 91 | 2174 |
|  sorting.SortDeeplyNestedFields | 38965 | 38965 | 324 | 156 | 4516 |
|  sorting.SortWithTopLevelCypher | 2119 | 2119 | 130 | 270 | 1040 |
|  unions.SimpleUnionQuery | 321 | 321 | 55 | 129 | 35 |
|  unions.SimpleUnionQueryWithMissingFields | 293 | 293 | 59 | 91 | 35 |
|  unions.NestedUnion | 398553 | 398553 | 297 | 337 | 33033 |
|  unions.NestedUnionWithMissingFields | 372527 | 372527 | 319 | 326 | 33033 |
|  update.NestedUpdate | 2119 | 2119 | 43 | 67 | 1040 |

</details>
        
Old Schema Generation: 33.451s
Schema Generation: 33.235s

**Comment by tbwiss** [comment]
[K8s Service reconciler](https://trello.com/c/z4dQSsOd/2093-k8s-service-reconciler)

**Review by darrellwarde — COMMENTED** [review]
I think the whole thing generally looks great. I'm going to submit 1 review now to potentially save wasted effort, because I generally have a lot of questions about the use of `Cypher.RawCypher` all over the place. In a lot of these instances, the native functionality exists in the Cypher Builder. Is the use of `RawCypher` in these instances a technical limitation or time saver?

**Comment by MacondoExpress** [comment]
Thank you for the review!

It's a mix of both, for instance, if a function returned `${alias}: ${value}` we don't have the concept of MapEntry that could then be used to construct the MapProjection, something like `new Cypher.MapEntry(node.property(alias), new Cypher.Literal(value))` and then having something along `new Cypher.MapProjection(node, entries)` that will generates `this0 { name: "Keanu" }`. 
But anyway not an  hard limit could not be avoided by changing the logic of the translation layer. 
The reality is that most of the effort was spent to move everything inside the CypherBuilder AST and the little time left was used to remove the `chainStr` and the `REPLACE_ME` mainly. 
Most of the `RawCypher` could be changed to the proper Cypher Clause with ease and relative speed, even now or with future refactoring iterations!

**Review by darrellwarde — APPROVED** [review]
As @MacondoExpress and I agree, there is further improvements to make in this area, but this marks a massive steps in the right direction! 🎉 Moving forward, we should keep tabs on the amount of `Cypher.RawCypher` we use, to ensure that we continue progressing. But I say let's merge this before too many conflicts creep in!!

**Pull request merged**
