### PR TITLE
Allow empty strings as CypherAnnotations

### LINKED ISSUE #2899: Incorrect @cypher annotation check
**Describe the bug**
`@cypher statement required` is showing even though no @cypher is used. This only happened during jest testing.

**Type definitions**

**To Reproduce**
A bit difficult, but the code does seem incorrect

**Expected behavior**
Message shouldn't show up

### PR DESCRIPTION
**Pull request by webberwang**
# Description

An empty string `""` will fail the check below.

## Complexity

Complexity: Low

# Issue

Closes #2899  

# Checklist

The following requirements should have been met (depending on the changes in the branch):

- [ ] Documentation has been updated
- [ ] TCK tests have been updated
- [ ] Integration tests have been updated
- [ ] Example applications have been updated
- [ ] New files have copyright header
- [ ] CLA (https://neo4j.com/developer/cla/) has been signed

### CODE REVIEW

**Comment by darrellwarde** [comment]
> [CLA assistant check](https://cla-assistant.io/neo4j/graphql?pullRequest=2900) Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/neo4j/graphql?pullRequest=2900) before we can accept your contribution.You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/neo4j/graphql?pullRequest=2900) it.

Thanks for the contribution @webberwang! Can I please ask you to sign the CLA using the link in the above message?

Additionally, due to being in an experimental phase of using a new CLA tool, can I ask you to also sign using our existing process? https://neo4j.com/developer/cla/#sign-cla

Sorry about the hassle of two tools, we hope to rectify this soon.

**Comment by webberwang** [comment]
> > [CLA assistant check](https://cla-assistant.io/neo4j/graphql?pullRequest=2900) Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/neo4j/graphql?pullRequest=2900) before we can accept your contribution.You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/neo4j/graphql?pullRequest=2900) it.
> 
> Thanks for the contribution @webberwang! Can I please ask you to sign the CLA using the link in the above message?
> 
> Additionally, due to being in an experimental phase of using a new CLA tool, can I ask you to also sign using our existing process? https://neo4j.com/developer/cla/#sign-cla
> 
> Sorry about the hassle of two tools, we hope to rectify this soon.

Just did both, thanks

**Comment by neo4j-team-graphql** [comment]
Made some changes to the GraphQL Toolbox? Or made some changes to the core library perhaps?

Check out your changes at https://neo4j-graphql-toolbox-stage-2900.surge.sh

Use for instance a local dbms hosted on [Neo4j Desktop](https://neo4j.com/download/) or a cloud-hosted [Aura Free](https://neo4j.com/cloud/aura-free/) dbms.

**Comment by neo4j-team-graphql** [comment]
# Performance Report

No Performance Changes


<details>
    <summary>Show Full Table</summary>
    
| name | dbHits | old dbHits | time (ms) | old time (ms) | maxRows |
| ---- | ------ | ---------- | --------- | ------------- | ------- |
|  aggregations.TopLevelAggregate | 3403 | 3403 | 33 | 42 | 1134 |
|  aggregations.NestedAggregation | 13514 | 13514 | 82 | 116 | 2174 |
|  aggregations.AggregationWithWhere | 10942 | 10942 | 64 | 101 | 2174 |
|  aggregations.AggregationWhereWithinNestedRelationships | 20101954 | 20101954 | 2921 | 2867 | 2008534 |
|  aggregations.AggregationWhereWithinNestedConnections | 20101954 | 20101954 | 2693 | 2815 | 2008534 |
|  aggregations.NestedCountFromMovieToActors | 8694 | 8694 | 56 | 82 | 2174 |
|  aggregations.NestedCountFromActorsToMovie | 8900 | 8900 | 77 | 73 | 2174 |
|  aggregations.DeeplyNestedCount | 12062292 | 12062296 | 4780 | 4915 | 2008534 |
|  batch-create.BatchCreate | 3600 | 3600 | 91 | 128 | 600 |
|  connect.createAndConnect | 12419 | 12419 | 302 | 209 | 3003 |
|  connections.Connection | 13042 | 13042 | 158 | 138 | 2174 |
|  connections.NestedConnection | 38231 | 38231 | 129 | 133 | 4516 |
|  connections.ConnectionWithSort | 2277 | 2277 | 68 | 70 | 1040 |
|  connections.ConnectionWithSortAndCypher | 2277 | 2277 | 178 | 319 | 1040 |
|  create.SimpleMutation | 6 | 6 | 29 | 36 | 1 |
|  cypher-directive.TopLevelCypherDirective | 99525 | 99525 | 735 | 820 | 10168 |
|  cypher-directive.TopLevelCypherDirectiveWithColumnName | 127992 | 127992 | 271 | 317 | 10168 |
|  delete.SimpleDelete | 18361 | 18361 | 213 | 217 | 1040 |
|  delete.NestedDeleteInUpdate | 17123 | 17123 | 149 | 227 | 2040 |
|  query.SimpleQuery | 14120 | 14120 | 170 | 152 | 2174 |
|  query.QueryWhere | 8673 | 8670 | 34 | 50 | 2165 |
|  query.SimpleQueryWithNestedWhere | 8844 | 8841 | 52 | 76 | 2165 |
|  query.Nested | 10084290 | 10084290 | 9917 | 10552 | 2008534 |
|  query.NestedWithFilter | 37172 | 37172 | 150 | 150 | 4511 |
|  query.OrFilterOnRelationships | 36221 | 36584 | 156 | 262 | 1589 |
|  query.OrFilterOnRelationshipsAndNested | 30148 | 30647 | 214 | 292 | 1589 |
|  query.QueryWithNestedIn | 13159 | 13426 | 56 | 63 | 1488 |
|  query.NestedConnectionWhere | 8794 | 8794 | 53 | 64 | 2174 |
|  query.DeeplyNestedConnectionWhere | 8823 | 8844 | 72 | 90 | 2174 |
|  query.DeeplyNestedWithRelationshipFilters | 6251 | 6251 | 120 | 151 | 1134 |
|  query.NestedWithRelationshipSingleFilters | 3021189 | 3021189 | 747 | 612 | 1003942 |
|  query.Fulltext | 96 | 96 | 36 | 33 | 16 |
|  query.FulltextWithNestedQuery | 571 | 571 | 40 | 49 | 84 |
|  sorting.SortMultipleTypes | 2493 | 2493 | 60 | 69 | 1040 |
|  sorting.SortMultipleTypesWithCypherWithCypher | 1390 | 1489 | 170 | 376 | 1040 |
|  sorting.SortOnNestedFields | 13042 | 13042 | 87 | 121 | 2174 |
|  sorting.SortDeeplyNestedFields | 38965 | 38965 | 120 | 177 | 4516 |
|  sorting.SortWithTopLevelCypher | 2119 | 2119 | 103 | 219 | 1040 |
|  unions.SimpleUnionQuery | 321 | 321 | 58 | 65 | 35 |
|  unions.SimpleUnionQueryWithMissingFields | 293 | 293 | 58 | 71 | 35 |
|  unions.NestedUnion | 398553 | 398553 | 328 | 342 | 33033 |
|  unions.NestedUnionWithMissingFields | 372527 | 372527 | 408 | 340 | 33033 |
|  update.NestedUpdate | 2119 | 2119 | 44 | 47 | 1040 |

</details>
        
Old Schema Generation: 33.224s
Schema Generation: 35.757s

**Comment by darrellwarde** [comment]
Hey @webberwang, trying to understand what is actually happening here and why this is happening. You're saying that you're getting this error when not even using the `@cypher` directive? Ideally we would see the code causing this. Additionally, whilst we could merge this; without any tests, this could easily be changed again, causing a regression. Please do consider whether you could add a test here.

**Comment by webberwang** [comment]
> Additionally, whilst we could merge this; without any tests, this could easily be changed again, causing a regression. Pleas

It's a bit hard to reproduce, only happens during our integration specs with Jest. Perhaps babel is the culprit, I'll try to provide a reproduction

**Comment by angrykoala** [comment]
As it is now, this will fail if the following is provided: `@cypher(statement: "")` which is correct IMO. 

The problem described here doesn't seem to be reproducible at the moment, so I'll close this issue.v @webberwang Feel free to comment here if you find a way to reproduce this issue

**Pull request closed without merging**
