### PR TITLE
Only warn about missing `features.authorization` once

### PR DESCRIPTION
**Pull request by darrellwarde**
# Description

If the authorization directives were used multiple times without `features.authorization` specified, there was a lot of duplicate warnings, which was very messy.

## Complexity

Complexity: Low

### CODE REVIEW

**Comment by neo4j-team-graphql** [comment]
Made some changes to the Neo4j GraphQL Toolbox? Or made some changes to the core library perhaps?

Check out your changes at https://neo4j-graphql-toolbox-3917.surge.sh

Use for instance a local dbms hosted on [Neo4j Desktop](https://neo4j.com/download/) or a cloud-hosted [Aura Free](https://neo4j.com/cloud/aura-free/) dbms.

**Comment by neo4j-team-graphql** [comment]
# Performance Report

No Performance Changes


<details>
    <summary>Show Full Table</summary>
    
| name | dbHits | old dbHits | time (ms) | old time (ms) | maxRows |
| ---- | ------ | ---------- | --------- | ------------- | ------- |
|  aggregations.TopLevelAggregate | 3403 | 3403 | 35 | 77 | 1134 |
|  aggregations.NestedAggregation | 16553 | 16553 | 92 | 117 | 2174 |
|  aggregations.AggregationWithWhere | 11979 | 11979 | 55 | 64 | 2174 |
|  aggregations.AggregationWhereWithinNestedRelationships | 22116987 | 22116987 | 3437 | 3450 | 2008534 |
|  aggregations.AggregationWhereWithinNestedConnections | 22116987 | 22116987 | 3105 | 3123 | 2008534 |
|  aggregations.NestedCountFromMovieToActors | 9734 | 9734 | 47 | 68 | 2174 |
|  aggregations.NestedCountFromActorsToMovie | 9937 | 9937 | 49 | 76 | 2174 |
|  aggregations.DeeplyNestedCount | 13070333 | 13070329 | 4811 | 5184 | 2008534 |
|  batch-create.BatchCreate | 4200 | 4200 | 162 | 195 | 600 |
|  batch-create.BatchCreateSmall | 77 | 77 | 76 | 146 | 11 |
|  connect.createAndConnect | 14424 | 14424 | 217 | 255 | 3003 |
|  connections.Connection | 14082 | 14082 | 72 | 104 | 2174 |
|  connections.NestedConnection | 45472 | 45472 | 137 | 151 | 4516 |
|  connections.ConnectionWithSort | 3284 | 3284 | 74 | 101 | 1040 |
|  connections.ConnectionWithSortAndCypher | 16325 | 16325 | 107 | 163 | 2174 |
|  create.SimpleMutation | 7 | 7 | 68 | 98 | 1 |
|  cypher-directive.TopLevelMutationDirective | 1135 | 1135 | 49 | 31 | 1134 |
|  delete.SimpleDelete | 19401 | 19401 | 258 | 247 | 1040 |
|  delete.NestedDeleteInUpdate | 19198 | 19198 | 157 | 182 | 1183 |
|  2925.SingleRelationshipFilter | 6468 | 6468 | 43 | 74 | 1040 |
|  2925.NestedSingleRelationshipFilter | 22900 | 22900 | 113 | 141 | 2174 |
|  2925.SingleRelationshipRequiredFilter | 5201 | 5201 | 42 | 54 | 1040 |
|  2925.NestedSingleRelationshipRequiredFilter | 9361 | 9361 | 82 | 81 | 1040 |
|  query.SimpleQuery | 3121 | 3121 | 24 | 29 | 1040 |
|  query.SimpleQueryWithRelationship | 16162 | 16162 | 48 | 76 | 2174 |
|  query.QueryWhere | 9718 | 9699 | 39 | 45 | 2169 |
|  query.SimpleQueryWithNestedWhere | 9896 | 9877 | 56 | 64 | 2169 |
|  query.Nested | 10096041 | 10096041 | 11250 | 11252 | 2008534 |
|  query.NestedWithFilter | 10074401 | 10074401 | 10276 | 11056 | 2004000 |
|  query.OrFilterOnRelationships | 41374 | 43619 | 178 | 267 | 1425 |
|  query.OrFilterOnRelationshipsAndNested | 35286 | 38198 | 219 | 339 | 1425 |
|  query.QueryWithNestedIn | 13962 | 13423 | 111 | 104 | 1402 |
|  query.NestedConnectionWhere | 9834 | 9834 | 61 | 109 | 2174 |
|  query.DeeplyNestedConnectionWhere | 9928 | 10029 | 87 | 136 | 2174 |
|  query.DeeplyNestedWithRelationshipFilters | 19152 | 19278 | 150 | 192 | 1598 |
|  query.NestedWithRelationshipSingleFilters | 3881 | 3881 | 185 | 242 | 1134 |
|  query.Fulltext | 80 | 80 | 39 | 49 | 16 |
|  query.FulltextWithNestedQuery | 587 | 587 | 50 | 54 | 84 |
|  sorting.SortMultipleTypes | 3515 | 3515 | 79 | 93 | 1040 |
|  sorting.SortMultipleTypesWithCypherWithCypher | 14515 | 14499 | 104 | 120 | 2174 |
|  sorting.SortOnNestedFields | 14082 | 14082 | 55 | 58 | 2174 |
|  sorting.SortDeeplyNestedFields | 43198 | 43198 | 99 | 109 | 4516 |
|  sorting.SortWithTopLevelCypher | 3396 | 3396 | 67 | 80 | 1040 |
|  unions.SimpleUnionQuery | 321 | 321 | 73 | 104 | 35 |
|  unions.SimpleUnionQueryWithMissingFields | 293 | 293 | 67 | 141 | 35 |
|  unions.NestedUnion | 410637 | 410637 | 288 | 414 | 33033 |
|  unions.NestedUnionWithMissingFields | 384611 | 384611 | 313 | 293 | 33033 |
|  update.NestedUpdate | 16143 | 16143 | 128 | 136 | 2002 |

</details>
        
Old Schema Generation: 46.146s
Schema Generation: 47.277s
Old Subgraph Schema Generation: 56.317s
Subgraph Schema Generation: 55.937s

**Review by a-alle — APPROVED** [review]
Looks good! 
I think the line is a bit blurry between validator rules vs filterDocument concerns. Given that it is just a console.warn and it doesn't lead to an "early return" I think it could be done nicer as a validator rule.

**Comment by darrellwarde** [comment]
> Looks good! I think the line is a bit blurry between validator rules vs filterDocument concerns. Given that it is just a console.warn and it doesn't lead to an "early return" I think it could be done nicer as a validator rule.

This wouldn't work as a validation rule right? AFAIK, each validation rule is run in isolation, so it would be quite janky to maintain state between them to only log once. Unless I'm misunderstanding.

**Review by a-alle — APPROVED** [review]
👍

**Pull request merged**
